// Copyright © 2026 Christopher Snow

// The words of the lesson compiler.
//
// Drafted by the course's prose process from briefs of checked facts
// (docs/notes/beyond-the-machine/briefs, briefs K1 to K4), checked against the model, and placed
// here by the lesson's structure. Edit a fact here only after checking it; the lesson's facts
// test holds the numbers.

export const PROSE = {
  question:
    'The generalisation of lesson 11.1 says: "The assembler translates line for word. It adds no instruction of its own: every word in the listing comes from one line you wrote." The generalisation of lesson 13.2 says: "Every program reaches a machine as machine code. Whatever language it was written in, the machine runs words like `A7345000`."\n\nModule 0\'s shop wanted the display to show how much warmer room A is than room B. Its program took four lines for that, lines 1 to 4. The shop would say it in one line: `display <= sensorA - sensorB`. Each of the four lines does one job, as the assembler requires.\n\nCan a program take a line that says what to work out, and write the instructions that work it out?',
  askedLead:
    'The debugger below holds two lines: `display <= sensorA - sensorB` and `stop`. You can edit them. The assembler refuses line 1 and gives its reason: "Each line is one instruction. Write it as a transfer, such as R3 <= R1 + R2." Read the refusal, then try writing line 1 the way the assembler asks.',
  motivation:
    "Such a program is a **compiler**. A compiler is a program that reads lines that say what to work out, and writes the instructions that work it out.\n\nSet against the assembler, the compiler does four things the assembler does not:\n\n- it writes several instructions for one line, where the assembler writes one word;\n- it chooses the registers;\n- it makes up a name for a line;\n- it turns a comparison over.\n\nThe compiler's lines are the course's own text with the assembler's refusals lifted. There are two forms. In the first, `D <= E`, D is `display` or `lamps`. In the second, `if E C E then D <= E`, C is one of `<`, `<=`, `>`, `>=`, `==` or `!=`.\n\nAn E is a device's name, a number, two Es joined by `+`, `-`, `&`, `|` or `^`, or an E in brackets. Jobs are done left to right, brackets first.\n\nOne trap sits in these lines. In the compiler's lines, a device's name stands for its word, the reading. In assembly, the name alone is its address: `R1 <= sensorA` assembles, and puts `7D8` in R1, the address of room A's sensor.\n\nThe compiler is a program in the page, as the assembler is. It refuses a name that is no device the line may read, a number that does not fit from -2048 to 2047, `*` and `/`, since the machine has no multiplication or division, and a line in neither form.",
  prediction:
    "The figure below compiles the shop's CLASH rule as one line: `if sensorA - sensorB >= 100 then lamps <= 4`. It has stopped after 4 instructions, and the line now reads `if R3 >= R4 then lamps <= 4`. Room A's reading went into R1, room B's into R2, the gap into R3, and 100 into R4. The compiler's next instruction deals with the `if`. Choose that next instruction, then press \"Check my prediction\".",
  p1Question: "Which branch does the compiler write next?",
  p1Explain:
    "The compiler writes `if R3 < R4 signed goto after1`. The branch jumps past `lamps <= 4` when the comparison fails, so it tests the comparison turned over: `>=` turned over is `<`. The readings can be of either sign, so the comparison is read signed. `after1` is a name the compiler makes up for the line after the rest.\n\nEach wrong option fails in one clause. `>=` is the comparison not turned over, so it would skip the lamps when the gap is 100 or more. `R4 < R3` swaps the registers, which is `>`, wrong here. `unsigned` reads a negative gap as a huge number.",
  investigation:
    "The figure offers two lines: the gap rule, `display <= sensorA - sensorB`, and the CLASH rule, `if sensorA - sensorB >= 100 then lamps <= 4`. Choose one and watch the compiler take it one piece at a time. For each piece, the figure shows the piece, the rule that applies to it, the instruction written, and the line as it now reads.",
  stepsLead:
    'Choose the gap rule. Press "Next instruction" until nothing of the line is left, and read the rule each time. Then press an instruction in the table to see which piece of the line it came from. Do the same with the CLASH rule. Try both readings at the end: the shop\'s, and room A at -100.',
  stepsOutcomes:
    "The gap line became 4 instructions and `stop`. With the shop's readings, the display shows 66. The CLASH line became 7 instructions and `stop`. At a gap of 66, CLASH stays dark. With room A at -100, the gap is 150, and CLASH lights. Every instruction comes from one piece of the line.",
  construction:
    "The compiled CLASH line now runs on the whole machine from Module 13, with the shop's readings. The figure stops before the branch's FETCH edge, edge 19. The IR takes a word at that edge, and the figure asks for that word. As in 13.2, work it out from the line `if R3 < R4 signed goto after1` and its fields. Kind 5 is a branch. Job 6 is \"less than, read signed\". A is R3, B is R4, and Y is unused. The constant counts the instructions the branch goes on, to `stop`.",
  branchLead:
    'Commit to the word first. Then press "Next edge" until the figure reaches edge 21, the branch\'s ALU edge. The condition block is open there. Watch MET and the PC as it does.',
  branchQuestion: "What word does the IR hold after the next edge?",
  branchExplain:
    'The IR takes `56340003`. K is 5, a branch. J is 6, less than, read signed. A is 3, for R3. B is 4, for R4. Y is 0, unused. The constant `003` is three instructions on: past `R5 <= 4` and the store, to `stop`.\nThe wrong options each break one field. `57340003` has job 7, "not less": the comparison is not turned over. `56430003` swaps R3 and R4. `56340007` counts the wrong distance.',
  branchAfter:
    "Before edge 21, MET was already 1. The ALU subtracts R4 from R3: 66 minus 100. The result is negative, so MINUS XOR OVER is 1. At edge 21, HR takes -34, and the PC takes `01C`, the address of `stop`. So CLASH stays dark. The line's `>=` is a comparison the machine has no instruction for. It ends at the condition block's gates, in MINUS XOR OVER, which Module 7 built.",
  failureExperiment:
    'The figure is the same compiler with one rule broken. Every piece now goes into R1, whatever is still waiting there. Before you press "Next instruction" to the end, predict what the display will show for the gap line. Then press through and check your prediction against the figure.',
  faultLead: 'Press "Next instruction" until nothing of the line is left, then try both readings.',
  faultOutcomes:
    "The instructions are `R1 <= word[sensorA]`, `R1 <= word[sensorB]`, `R1 <= R1 - R1`, and `word[display] <= R1`. The second load writes over room A's reading before the subtraction reads it. `R1 - R1` is 0, so the display shows 0. The display shows 0 with the shop's readings, and also with room A at -30 and room B at 80. A register holds a piece until the job that uses it has read it. So the compiler must know which registers still hold pieces that wait.",
  explanation:
    "The compiler follows 5 rules. Four follow advice the assembler gave in lesson 11.1 when it refused a line.\n\n1. A device's name the line reads. 11.1 has no refusal for this one. The rule writes the device's word into the next register: `R1 <= word[sensorA]`.\n2. A number. 11.1 said: \"Put the number in a register first.\" The rule does that: `R4 <= 100`.\n3. Two registers joined by a job. 11.1 said: \"One line does one job.\" The rule writes the result into the next register: `R3 <= R1 - R2`.\n4. `if`, once both sides are registers. 11.1 said: \"After < or >=, write signed or unsigned.\" The rule writes a branch past the rest of the line, on the comparison turned over, which is its opposite. For `<`, that is `if R3 >= R4 signed goto after1`.\n5. A device's name the line writes. 11.1 said: \"A store writes a register's word.\" The rule writes the store: `word[lamps] <= R5`.\n\nEach line starts again at R1, so nothing stays in a register from one line to the next. The program ends with `stop`. Where the comparison turned over is `>` or `<=`, the machine has no branch for it, so the compiler swaps the two registers, as lesson 10.3 did.\n\nThe gap line's instructions are Module 0's lines 1 to 4, and the CLASH line's are Module 0's lines 1 to 3 and 5 to 9. Your first program in the course was these two outputs, with the gap worked out once instead of twice.",
  generalisation:
    "The figure below puts the compiler's program for both lines beside Module 0's.\n\nModule 0's program keeps the gap in R3 for its second rule. The compiler works the gap out again, because each line starts afresh.\n\nA better compiler does more, and this page does not teach it. It keeps a value in a register for a later line. It leaves a number in an instruction's constant where it fits, as 10.3's immediate does. It keeps a comparison as a word, using set if (10.5). Real languages add loops, functions and names the program makes up for its own values. A function call follows the calling convention of 11.3.",
  compareLead:
    "Press the figure's run button. Compare how many instructions each program has, how many it runs, and what each leaves on the display.",
  challengeLead:
    "Here you write the instructions the compiler's 5 rules give for a line that no figure compiles.",
  c1Task:
    "Write the instructions the compiler's 5 rules give for this line, which no figure compiles:\n\n`if sensorB - sensorA > 100 then lamps <= 4`\n\nThe shop wants CLASH when room B is more than 10.0 degrees warmer than room A. This line mends what Module 0's failure experiment showed. Room B's freezer failed and read -50, and CLASH stayed dark, because the program checked one way only.\n\nThe box starts with the line as a comment and `stop`. Write your instructions in the box, before `stop`. 6 runs test your program. Each sets room A and room B, then checks the lamps, that the display is still 0, and that the run ends at your `stop`. The runs set room A and room B to -184 and -50, -250 and -150, -250 and -149, -184 and -250, -30 and 80, and 20 and 25; CLASH must light in the first, third and fifth. The runs judge what the line means, so any instructions that do what it says pass. Write the rules' instructions anyway. A run that fails names the rule it points to.",
  reflection:
    "The course's final demonstration now starts one level higher. It starts with a line as the shop says it, then follows that line through its instructions, its words, its edges and its gates.\n\nThink about two questions. Which rule was hardest to apply by hand? Where did the compiler write more than you would have?\n\nThe author's book *Systems From Scratch* follows a real compiler. Its chapter [What a Computer Does With a Program](https://snowch.github.io/computer-systems/what-a-computer-does-with-a-program/) follows one command through the 4 programs it runs: the preprocessor, the compiler, the assembler and the linker. [Reading a Listing](https://snowch.github.io/computer-systems/reading-a-listing/) reads what a real compiler made of one small function, and [Machine-Level Code on RISC-V](https://snowch.github.io/computer-systems/machine-level-code-on-riscv/) shows a real compiler's registers, its stack and its comparisons and branches.",
  modelVsReality:
    "This compiler reads one kind of line. It keeps nothing between lines, and it writes the same instructions every time it reads the same line. A real compiler reads a whole language, with loops, functions and names of its own. It chooses among many ways to write the same work. It keeps values in registers across lines. It checks the whole program before it writes anything. It still ends where this one does: in instructions an assembler turns into machine code.",
  c1Hints: [
    "The branch jumps past the rest of the line when the comparison fails.",
    "A common mistake is to copy the `<` that the figure writes for the CLASH rule. With `<`, CLASH lights when room B is exactly 10.0 degrees warmer, a gap of exactly 100.",
    "Take `if R6 == R9`. Turned over, it is `R6 != R9`, so the compiler writes `if R6 != R9 goto after1`.",
    "The first four instructions are `R1 <= word[sensorB]`, `R2 <= word[sensorA]`, `R3 <= R1 - R2` and `R4 <= 100`.",
    "```\nR1 <= word[sensorB]\nR2 <= word[sensorA]\nR3 <= R1 - R2\nR4 <= 100\nif R4 >= R3 signed goto after1\nR5 <= 4\nword[lamps] <= R5\nafter1: stop\n```\n\n`R3 > R4` turned over is `R3 <= R4`, which the machine writes as `R4 >= R3`.",
  ],
} as const;
