// Copyright © 2026 Christopher Snow

// The words of the lesson final-machine.
//
// Drafted by the course's prose process from briefs of checked facts
// (docs/notes/module-13-machine/briefs, briefs 4A to 4C), checked against the simulator, and
// placed here by the lesson's structure. Edit a fact here only after checking it; the lesson's
// facts test holds the numbers.

export const PROSE = {
  question:
    "Lessons 1 to 3 showed the whole machine, its three blocks and the joins between them, and followed a line down to one gate. You built and tested every part in an earlier module, and the joins were drawn for you. This lesson asks you to write the joins yourself, as text. Can you join the parts into the whole machine so that it runs every program as the instruction-level model does? That model works out each instruction in numbers, with no gates. The figure below runs the course's own text on the seven programs the lab's tests run.",
  questionLead: 'Choose a program and press "Run it"; try each of the seven.',
  motivation:
    "Modules 8 to 10 wrote the machine as text. You placed its parts by name and joined them with wires.\n\nHere you write the top module of the whole machine, `machine`, in the subset Modules 8 to 10 used. It needs no new construct. The course supplies nine parts: `memory`, `decoder`, `system`, `controller`, `traplogic`, `cregs`, `registers`, `alu` and `condition`. You write the joins between them, and the small parts between them. These are:\n\n- the PC;\n- the address the memory reads;\n- the IR;\n- the held words HA, HB, HR and HM;\n- USER and IE, from C0;\n- TICK, which tells the timer to count;\n- the constant made a word, WIDE;\n- the ALU's two inputs;\n- the word register Y takes;\n- the target of a branch;\n- the next PC.\n\nThe parts are the course's own versions of the parts you designed. The machine does not run your earlier answers. The joins are yours.\n\nSeven programs test your machine, and each reaches a different part of it. Each count is the instructions and traps that run has.\n\n- The shop's program: a set if, a call through a register, a system call and `resume`. 19 instructions and traps.\n- A fault in user mode: user mode refuses a device's address, with cause `32`. 11 instructions and traps.\n- A system call, then the timer: the program sets the timer to 4 at `00C` and makes a system call at `018`. The timer later interrupts it, with cause `81`. 17 instructions and traps.\n- The door: the door opens while the program runs, and the program is interrupted, with cause `82`. 10 instructions and traps.\n- Signs, bytes and WARM: a constant whose sign matters (-5), a set if whose condition holds, a comparison read unsigned, a subtraction that overflows, a byte stored and loaded, the word of DOOR and WARM read with WARM at 1, and a call to a label above the call. 15 instructions and traps.\n- A system job in user mode: the program drops to user mode and runs `stop`, which user mode refuses, with cause `22`. The handler shows the cause. 11 instructions and traps.\n- A store to the ROM: with no handler, the store traps with cause `34`, and the machine halts. 2 instructions and traps.\n\nEach program runs on your machine and on the model. The comparison is made after every instruction and every trap. A test fails at the first instruction or trap after which the two disagree. Its sentence names that line, its address, what differs, and the value on your machine and by the model. It does not name the join. Finding the join from that sentence is the skill this lesson teaches.",
  prediction:
    "The text in this figure changes one line: `assign TICK = PCEN;`. TICK tells the timer to count down by one. PCEN, the PC's enable, is 1 at an edge where an instruction finishes. It is also 1 at an edge that traps, where the PC takes the handler's address.\n\nModule 12's rule holds that a trap's edge finishes no instruction, so the timer does not count it. The timer program sets its timer to 4 at `00C`, then makes its system call at `018`.\n\nNo result shows until you commit. Choose an answer and press \"Check my prediction\".",
  p1Question: "Which of the two programs disagrees with the model on this text?",
  p1Explain:
    'Only "A system call, then the timer" disagrees: "After `call system` at `018`, the timer is 1 on the machine and 2 by the model."\n\nThe program sets the timer to 4. `R1 <= 3` and `C0 <= R1` finish, so the timer is 2. `call system` traps. The model does not count a trap\'s edge, but this text does.\n\nThe shop\'s program sets no timer, so it never shows the count wrong. A test finds a wrong line only where its program reaches it.',
  investigation:
    'Three texts, each the course\'s own with one line changed: "Every branch taken", "Interrupts on in system mode" and "A call keeps the PC". Each changed line is wrong. Which programs find each one? Here is what each line should do. A branch goes to its target only when MET holds. IE says interrupts are on, and it is C0\'s bit 1. A call writes the PC plus 4 into the register Y names.',
  invLead:
    'Run each text on each program and note which programs disagree. The paragraph below, under "The runs so far", shows once every run it reports has been made.',
  invAfter:
    'Only the timer program disagrees on "Every branch taken". Its sentence reads: "After `if R5 == R6 goto back` at `038`, the PC is 044 on the machine and 03C by the model."\n\nTwo programs disagree on "Interrupts on in system mode": the timer program and the door program. Their sentences read: "After `if R5 == R6 goto back` at `038`, the PC is 030 on the machine and 044 by the model." and "At `R5 <= C3` at `020`, the machine halts with cause `82`; the model does not halt."\n\nTwo programs disagree on "A call keeps the PC": the shop\'s program and "Signs, bytes and WARM". Their sentences read: "After `call R6, R15` at `02C`, R15 is 44 (02C) on the machine and 48 (030) by the model." and "After `call twice, R15` at `034`, R15 is 52 (034) on the machine and 56 (038) by the model."\n\nNo one program finds every wrong line.',
  construction:
    '1. Three buttons sit above the text: "Start from the outline", "Start from the parts" and "Start from nothing". Changing to another start replaces your text, and the page asks first if you have changed it.\n2. "Start from the outline" gives the course\'s own text with six joins left out. This is where the lab starts. The text elaborates, and every test fails until the joins are written.\n3. Each of the six lines is marked with a comment beginning `JOIN:`. The line holds a constant or nothing in place of the join.\n4. "Start from the parts" places every part, lists all its ports and joins none. The wires are declared. Each part\'s brackets are empty, and the page\'s message names the first port not joined.\n5. The wires keep the names lesson 1\'s drawing uses. A port usually joins the wire of the same name, but not always: the memory\'s port `LOAD` takes the controller\'s `MLOAD`.\n6. Under your text, the drawing shows the joins your text makes. It is a map of the nine parts, and each part says how many of its ports are open. Choose a part to see its ports. Each port has a wire to what feeds it or reads it, or an open ring. The map shows only what you wrote.\n7. Press "Run tests". It runs all seven programs, each its own test. The failures are listed in the programs\' order. Each program\'s lines, with their addresses, are folded under your text by name.',
  failureExperiment:
    'The figure\'s text has one join wrong. Run all seven programs.\n\nRead the one sentence that differs, and decide which join you would look at. Once the door program has run, the button "Show the line this text changes" appears. Press it only once you have decided.',
  failLead: 'Run the seven programs on "A text with one join wrong".',
  failAfter:
    'Six programs agree with the model. None of them opens the door.\n\nThe door program does not agree: "After `R2 <= R2 + 1` at `014`, "waiting" is 00 on the machine and 10 by the model."\n\nBit 1 of "waiting" is the door\'s event. The model has it after the sixth instruction. The machine does not. The memory keeps "waiting", so look at what the memory takes for the door.\n\nPress "Show the line this text changes" to see it. It gives the memory\'s DOOR port `1\'b0`, a constant 0, in place of the machine\'s DOOR input.\n\nA failed test\'s sentence names a value. Ask which part makes that value, and what that part takes in.',
  explanation:
    "The comparison finds a wrong join at the first instruction or trap its effect reaches, not at the end of the program.\n\nA wrong line shows only where a program reaches it. The timer's count shows only at an edge that traps while the timer runs. A branch's condition shows only where a branch is not taken. The door shows only where it opens.\n\nThe sentence names a value, and that value points at a part. Look up the part in this list:\n\n- the PC: the next PC's choice, or a trap or `resume` that set it;\n- a register: the word register Y takes, or the register file's write;\n- C0 to C4: the control registers. C0 holds the mode and whether interrupts are on; at a trap it takes `01`, and at `resume` it takes C1. C1 takes C0 at a trap. C2 takes the return point and C3 takes the cause at a trap. C4 holds the handler's address, which the program writes;\n- the timer or \"waiting\": the memory's events, and what the memory takes in;\n- a byte of the RAM (a sentence such as \"byte 401 is 255 on your machine and unknown by the model\"): the memory, and the store that wrote it;\n- a halt or a stop where the model goes on, or the reverse: the trap logic, which decides both a halt and a stop (it holds Module 9's stop logic), and what it takes in.",
  generalisation:
    'Lesson 1\'s "Testing the joins" says that a join is tested only by running whole programs. Teams that design a CPU test them as this lesson did: the same programs run on the design and on a model, with the comparison as this lesson made it. They run many more programs than seven, many of them made at random. They also measure which parts the programs reached.\n\nPrograms that agree do not prove a design right. They show only that no program reached a wrong part. The text with one join wrong agreed with the model on six of the seven programs.\n\nThe fix is a program that reaches the part, as the door program reaches the door.',
  labLead:
    "Write the top module, `machine`, of the whole machine; the three buttons above the text give three ways in.",
  c1Task:
    'Write the top module, `machine`, of the whole machine in the course\'s SystemVerilog, in the subset Modules 8 to 10 used. The machine\'s ports are given, and you keep them: the inputs CLK, RST, DOOR, WARM, SENSORA and SENSORB, and the outputs PC, S (the controller\'s state), HALT, CAUSE, DISPLAY and LAMPS. The course supplies nine parts, `memory`, `decoder`, `system`, `controller`, `traplogic`, `cregs`, `registers`, `alu` and `condition`, and you place them by name. They are the course\'s own versions of the parts you designed. Your text joins them and writes the small parts between them.\n\nYou can start three ways. "Start from the outline" gives the course\'s text with six joins left out, each marked `JOIN:`; this is where the lab starts. "Start from the parts" places every part, lists its ports and joins none. "Start from nothing" gives the machine\'s ports alone.\n\nThe tests run seven programs from the reset, on your machine and on the model. The comparison covers the PC, the sixteen registers, the control registers, the display, the lamps, the timer, "waiting", the RAM\'s bytes, and whether each has stopped or halted. A failure names the line, its address, what differs and the two values. It never names the join.',
  reflection:
    "You joined the course's parts into the whole machine, and seven programs tested it. Ask yourself which failure sentence led you to which join, and which join took longest to find. Next, write a program of your own, run it on the whole machine, and trace it down to the gates.",
  modelVsReality:
    "Here the machine you wrote and the model run side by side in your browser, one instruction at a time.\n\nReal teams also check that the tools which turn a design's text into gates kept its meaning. They check it with a proof, for every input, not with programs. The course does not teach this.",
  c1Hints: [
    "Start from the outline and run the tests first. Each failure is a program that reaches one of the six `JOIN:` lines.",
    'A common mistake is looking for the wrong join at the line the sentence names. That line shows only where the wrong value first reached the comparison. A PC that differs after a trap points at the next PC\'s choice. C0 to C4 point at the control registers and what they take in. A wrong timer or "waiting" points at the memory.',
    "Here is a smaller example, which is not part of this task. In the figure's \"Every branch taken\", the timer program's sentence names the PC after a branch. The PC points at the next PC's choice, where the branch's condition, MET, comes in.",
    "The trap logic decides at every edge whether to trap. It needs the events waiting in the memory and whether a handler is set, which the control registers know. User mode is C0's bit 0 turned over, since bit 0 is 1 in system mode. The control registers give C0 as `STATUS`.",
    "C3 takes a trap's cause from the trap logic. Set if writes MET, the branch condition, as a whole word, 0 or 1, when SET is 1. A trap's edge gives the PC the handler's address, which the control registers give as C4.",
  ],
} as const;
