// Copyright © 2026 Christopher Snow

// The words of the lesson final-machine.
//
// Drafted by the course's prose process from briefs of checked facts
// (docs/notes/module-13-machine/briefs, briefs 4A to 4C), checked against the simulator, and
// placed here by the lesson's structure. Edit a fact here only after checking it; the lesson's
// facts test holds the numbers.

export const PROSE = {
  question:
    "Lessons 1 to 3 showed the whole machine. It has three blocks: the control unit, the datapath and the memory port. Each block opens to show the parts inside it. Joins carry values between the blocks. Lesson 3 traced one line of a program down to one gate.\n\nEvery part of the machine was built and tested in an earlier module. The joins between those parts were drawn for you.\n\nThis lesson asks you to write the joins yourself, as text. Can you join the parts into the whole machine so that it runs every program the way the instruction-level model does? That model works out what each instruction does, in numbers, with no gates.\n\nThe figure below runs the course's own text of the whole machine. It has the five programs the lab's tests run.",
  questionLead:
    'Choose a program and press "Run it". Each run compares the machine with the model after every instruction and every trap. Try all five.',
  motivation:
    "Modules 8 to 10 wrote the machine as text. The text placed parts by name and joined them with wires, as the drawing joins blocks.\n\nIn this lesson you write the top module of the whole machine, `machine`, in the course's SystemVerilog. It uses the subset Modules 8 to 10 used. No new construct is needed. The course supplies nine parts: `memory`, `decoder`, `system`, `controller`, `traplogic`, `cregs`, `registers`, `alu` and `condition`. You write the joins between them, and the small parts between them:\n\n- the PC;\n- the address the memory reads;\n- the IR;\n- the held words HA, HB, HR and HM;\n- the constant made a word (WIDE);\n- the ALU's two inputs;\n- the word register Y takes;\n- the target of a branch;\n- the next PC.\n\nThe course's parts are not your own earlier answers. Each lesson keeps its own work. Each of the course's parts passes the tests your part passed in its module. The joins are yours.\n\nFive programs test your machine. Each reaches a different part of the machine. Each runs on your machine and on the model, and the two are compared after every instruction and every trap:\n\n- The shop's program: a set if, a call through a register, a system call and `resume`. 69 edges.\n- A fault in user mode: the read of room A's sensor traps with cause `32`, because user mode refuses a device's address. 36 edges.\n- A system call, then the timer: the timer runs out and interrupts the program with cause `81`. 53 edges.\n- The door: the door opens while the program runs, and the program is interrupted with cause `82`. 31 edges.\n- A store to the ROM: a store to `010` traps with cause `34`, and with no handler the machine halts. 7 edges.\n\nA test fails at the first instruction or trap after which the two disagree. Its sentence names that line, its address, what differs, and the value on your machine and by the model. It does not name the join. Finding the join from that sentence is the skill this lesson teaches.",
  prediction:
    "The text in this figure changes one line: `assign TICK = PCEN;`.\n\nTICK tells the timer to count down by one. PCEN, the PC's enable, is 1 at an edge where an instruction finishes. It is also 1 at an edge that traps, where the PC takes the handler's address from C4.\n\nModule 12's rule: a trap's edge finishes no instruction, so the timer does not count it.\n\nNo result shows until you commit to an answer. Choose one and press \"Check my prediction\".",
  p1Question: "Which of the two programs disagrees with the model on this text?",
  p1Explain:
    'Only "A system call, then the timer" disagrees. Its run: "After `call system` at `018`, the timer is 1 on the machine and 2 by the model."',
  Why: "the program sets the timer to 4. `R1 <= 3` and `C0 <= R1` finish, so the timer is 2. `call system` traps. The model does not count a trap's edge. This text does.\n\nThe shop's program sets no timer, so it never shows the timer's count wrong. A test finds a wrong join only where its program reaches it.\n\nRun both programs in the figure to see each result.",
  investigation:
    'The figure has three texts. Each is the course\'s text with one line changed: "Every branch taken", "Interrupts on in system mode" and "A call keeps the PC". Each changed line is wrong. The figure has all five programs. Your question is which programs find each wrong line. The lines should do these things. A branch goes to its target only when MET holds. IE is C0\'s bit 1, and it says interrupts are on. A call writes the PC plus 4 into the register Y names.',
  invLead:
    "Run each text on each program, and note which programs disagree with the instruction-level model.",
  invAfter:
    '"Every branch taken": only the timer program disagrees. After `if R5 == R6 goto back` at `038`, the PC is 044 on the machine and 03C by the model. The other four programs have no branch, so they agree.\n\n"Interrupts on in system mode": the timer program and the door program disagree. In the timer program, the PC is 030 on the machine and 044 by the model after `if R5 == R6 goto back` at `038`. In the door program, the machine halts with cause `82` at `R5 <= C3` at `020`, the handler\'s first instruction, which traps again. The model does not halt.\n\n"A call keeps the PC": only the shop\'s program disagrees. After `call R6, R15` at `02C`, R15 is 44 on the machine and 48 by the model. The other four programs make no call.\n\nSo no one program finds every wrong line. The five programs together reach every join of the machine that the lab asks for.',
  construction:
    '1. There are three ways in, each a button above the text: "Start from the outline", "Start from the parts" and "Start from nothing". The outline is where it starts. Changing to another start replaces your text, and the page asks first if you have changed it.\n2. In the outline, six lines are marked with a comment beginning `JOIN:`. Each holds a constant, or nothing, where a join belongs. The text elaborates and runs, and every test fails.\n3. Each `JOIN:` comment names the join in words, such as where a value comes from. Read it, find the wire or the port that carries that value, and write it in place of the constant.\n4. In the parts start, every port is listed with nothing in its brackets, such as `.ADDR()`. Until a port is joined, the text does not elaborate, and its message names the first port that is not joined. You also write the small parts between the course\'s parts.\n5. The wires keep the names the drawing uses. A port usually joins the wire of the same name, but not always. For example, the memory\'s port `LOAD` takes the controller\'s `MLOAD`.\n6. Press "Run tests" to run all five programs. Fix the first failure in the list first.',
  failureExperiment:
    "The figure's text gives the memory's DOOR port `1'b0`, a constant 0, in place of the machine's DOOR input. The door never reaches the memory.\n\nRun all five programs before reading on. Then read the one sentence that differs, and decide which join you would look at.",
  failLead: 'Run the five programs on "DOOR held at 0".',
  failAfter:
    'Four programs agree with the model: none of them opens the door.\n\nThe door program: After `R2 <= R2 + 1` at `014`, "waiting" is 00 on the machine and 10 by the model.\n\nBit 1 of "waiting" is the door\'s event. The model has it after the sixth instruction; the machine does not. So the door\'s event never reached "waiting", which the memory keeps. Look at what the memory takes for the door.\n\nA sentence of the comparison names a value. Ask which part makes that value, and what that part takes in. That join is the first to read.',
  explanation:
    "A wrong join is found at the first instruction or trap whose effect reaches it. The comparison runs after every instruction and every trap, against the instruction-level model. It does not wait for the end of the program.\n\nA wrong join shows only where a program reaches it. The timer's count shows its fault only on an edge that traps while the timer runs. A branch's condition shows its fault only where a branch is not taken. The door shows its fault only where the door opens.\n\nWhat the failure sentence names points at a part:\n\n- the PC: the next PC's choice, or a trap or `resume` that set it;\n- a register: the word register Y takes, or the register file's write;\n- the timer or \"waiting\": the memory's events, and what the memory takes in;\n- a halt where the model goes on, or the reverse: the trap logic, and what it takes in.",
  generalisation:
    'Teams that design a CPU check their designs the same way. They run the same programs on the design and on a model that works out each instruction in numbers. They compare the two after every instruction.\n\nThey run many more programs than five, many of them made at random. They also measure which parts of the design the programs reached.\n\nPrograms that agree do not prove a design right. They show only that no program reached a wrong part. The change "DOOR held at 0" passes four of the five programs.\n\nThe fix is a program that reaches the part, as the door program reaches the door.',
  labLead:
    "Write the top module, `machine`, of the whole machine; the three buttons above the text give three ways in.",
  c1Task:
    "Write the top module, `machine`, of the whole machine. Its ports are given, and they stay as they are:\n\n- inputs `CLK`, `RST`, `DOOR`, `WARM`, `SENSORA` and `SENSORB`;\n- outputs `PC`, `S` (the controller's state), `HALT`, `CAUSE`, `DISPLAY` and `LAMPS`.\n\nThe course supplies nine parts as modules. Place them by name: `memory`, `decoder`, `system`, `controller`, `traplogic`, `cregs`, `registers`, `alu` and `condition`. Each of the course's parts passes the tests your own part passed in its module. The machine does not run your answers from earlier lessons. Each lesson keeps its own work.\n\nYour text joins these parts and writes the small parts between them.\n\nThree ways in, each a button above the text:\n\n- **Start from the outline**: the course's text with six joins left out, each marked `JOIN:`. This is where the lab starts.\n- **Start from the parts**: every part placed, all its ports listed, none joined.\n- **Start from nothing**: the machine's ports alone.\n\nThe tests run five programs on your machine and on the model, from the reset. After every instruction and every trap, the two are compared: the PC, the sixteen registers, the control registers, the display, the lamps, the timer, \"waiting\", and whether each has stopped or halted. A test fails at the first instruction or trap after which they disagree. Its sentence names that line, its address, what differs, and the value on your machine and by the model. It never names the join.",
  reflection:
    "You joined the course's parts into the whole machine. Five programs then ran on it and on the model, and they were compared after every instruction.\n\nAsk yourself: which failure sentence led you to which join, and which join took longest to find?\n\nNext: you write a program of your own, run it on the whole machine, and trace it down to the gates.",
  modelVsReality:
    "The course's comparison runs the model and your machine side by side, in the same browser.\n\nReal teams that design a CPU do the same, at far greater scale. The model is a program that works out each instruction in numbers. The design runs in a simulator of its gates or of its text. The two are compared after every instruction.\n\nTheir tests run millions of instructions, many from programs made at random.\n\nSome checks are proofs about the design for every input rather than tests of chosen programs. The course does not teach them.",
  c1Hints: [
    "Start from the outline. Run the tests first: each failure is a program that reaches one of the six `JOIN:` lines.",
    'Read a failure for the value it names, then ask which part makes that value. A PC that differs after a trap points at the next PC\'s choice. A wrong timer or "waiting" points at the memory.',
    "The trap logic decides, at every edge, whether to trap. It needs to know the events waiting in the memory and whether a handler is set. The control registers know whether a handler is set.",
    "User mode is C0's bit 0 turned over, since bit 0 is 1 in system mode. The control registers give C0 as `STATUS`. C3 takes a trap's cause from the trap logic.",
    "Set if writes MET, the branch condition, as a whole word, 0 or 1, when SET is 1. A trap's edge gives the PC the handler's address, which the control registers give as C4.",
  ],
} as const;
