// Copyright © 2026 Christopher Snow

// The words of the lesson instruction-set.
//
// Drafted by the course's prose process from briefs of checked facts
// (docs/notes/module-10-instruction-set/briefs), checked against the simulator, and placed
// here by the lesson's structure. Edit a fact here only after checking it; the lesson's
// facts test holds the numbers.

export const PROSE = {
  question:
    "Module 9 ended on a question. Which instructions a machine has is a choice, and so is how their words are laid out. Why are the course's instructions the ones they are?\n\nBefore that question, this lesson settles what a program can rely on.\n\nTwo machines in the course run the same programs. Module 8's machine takes one edge for each instruction. Module 9's takes 2 to 5 edges, with one memory port, an IR register and held words.\n\nBoth ran the colder-room program and showed -250 on the display.\n\nWhat is the same between the two machines? What can a program rely on, whichever machine runs it?",
  motivation:
    "The two machines have different parts. Module 9's machine has an IR register, held words HA, HB, HR and HM, and the controller's state. Module 8's has none of these. Its IR is a bus: the ROM's output at the PC.\n\nBoth have R0 to R15, the PC, the memory (the ROM and the RAM) and the shop's devices.\n\nThe course ran Module 8's 37 programs on Module 9's machine. After every instruction, the two machines agreed on every register, the PC, the memory and the devices.",
  prediction:
    "The figure runs the colder-room program on both machines side by side. Module 9's machine has made 3 edges of the first instruction, the load R2 ← memory[`7D8`]: FETCH, READ and ALU. It is in MEMORY. Module 8's machine takes its one edge for an instruction when Module 9's machine ends that instruction. So it has not run the load yet. Choose an answer and press \"Check my prediction\". The figure then shows its tables and its buttons.",
  p1Question: "Of the PC, R2, R3 and the display, what do the two machines differ on now?",
  p1Explain:
    "Nothing. Both PCs hold `000`. R2 and R3 are X on both machines. Both displays show 0. Module 9's machine has changed only its own parts: its IR holds `380027D8`, the load, and HR holds `7D8`, the address. The load writes R2 at its last edge, WRITE. The PC moves at that edge too. In Module 9's machine, every change a program can see happens at the edge that ends the instruction: a register written, the memory or a device written, the PC moved.",
  sideBySideLead:
    'This figure runs the colder-room program on both machines from the start, so you can compare them.\n\nThe table "What a program can see" shows the PC, R2, R3 and the display on each machine, and marks a row "differs" where the two machines differ.\n\nThe table "What Module 9\'s machine keeps of its own" shows the controller\'s state, IR, HA, HB, HR and HM. Module 8\'s machine has none of these parts.\n\nPress "Clock edge (Module 9\'s)" to move Module 9\'s machine one edge. When that edge ends an instruction, Module 8\'s machine also takes its one edge for the same instruction. Press "Next instruction" to make edges until the instruction ends. Press "Run until it stops" or "Start again".\n\nThe table "Instructions run" lists each instruction, the edges each machine takes, and whether the machines agree when the instruction ends.',
  sideBySideAfter:
    "The program runs 6 instructions, the stop among them.\n\nModule 8's machine takes 1 edge for each: 6 in all.\n\nModule 9's takes 5, 5, 3, 4 and 4 edges, then 2 for the stop: its fetch, and the edge at which it halts the machine in READ. 23 in all.\n\nAfter every instruction, the machines agree on the PC, R2, R3 and the display. The figure also checks every other register, the RAM and the devices: all agree. Both displays show -250.\n\nBetween instructions, Module 9's machine holds words in its IR, HA, HB, HR and HM. Module 8's machine has no parts for them.",
  construction:
    "A program sees a part of the machine only through an instruction: through a field that names a register, an address a load or a store reaches, or the PC, which branches, calls and jumps move.\n\nRunning an instruction moves the circuit's own parts too, but no field, address or PC reaches them, so the program does not see them. No field names HB or HM.\n\nEvery machine that runs the same programs must agree, after every instruction, on what a program can see. What a circuit does with its own parts is its own choice.",
  sortPartsLead:
    "Sort each part: one that every machine must agree on, or one that a circuit keeps of its own.",
  c1Task:
    'For each of nine parts, choose "Every machine agrees on it" if a program can see it, through a field, an address or the PC; or "One circuit\'s own" if no program can.\n\nThe parts are: R7, the PC, the IR, HR, the controller\'s state, the word at `400` in the RAM, the display, HA and the timer\'s count.\n\nThere are 9 tests. Each test names the part and the choice you made.',
  c1Hints: [
    "Ask whether a program can see the part: through a field, an address or the PC.",
    "A common mistake: counting the IR as a part every machine agrees on because Module 8's machine also has an IR. In Module 8's machine, the IR is a bus, the ROM's output at the PC. It is not a register. No instruction names it.",
    "A smaller example. R7: a register job can name R7 as A, B or Y, so every machine agrees on it. HR: no field names it, so it is one circuit's own.",
    "Part of the answer. Branches, calls and jumps move the PC. Loads and stores reach the word at `400` and the display. The timer is a device at `7E8` that loads and stores can reach. It counts instructions, not edges.",
    "The whole answer. Every machine agrees on R7, the PC, the word at `400`, the display and the timer's count. The IR, HR, the controller's state and HA are one circuit's own.",
  ],
  compareFaultsLead:
    'This figure runs the colder-room program on both machines, with a fault you choose in Module 9\'s machine.\n\n"HOLDR stuck at 1" means HR takes the ALU\'s result at every edge, not only when the state is ALU.\n\n"PCEN stuck at 1" means the PC takes its next value at every edge, so every edge ends an instruction.\n\nChoose a fault and press "Run until it stops".\n\nBefore you press, say for each fault whether the two machines will still agree after every instruction.',
  faultHoldr:
    "**HOLDR stuck at 1**\n\nThe machines agree after every instruction. Both displays show -250.\n\nHR takes a word at every edge. After the ALU edge it takes the same result again, because HA, HB and the IR do not change until the next fetch. At FETCH and READ it takes words that no later edge reads.\n\nThe course ran Module 8's 37 programs on both machines with this fault. None differs on what a program can see.",
  faultPcen:
    "**PCEN stuck at 1**\n\nThe machines differ after the first edge, on R2.\n\nThe controller still takes the load's 5 edges, FETCH to WRITE, but the PC moves on at every one of them. Each of those edges ends an instruction, so Module 8's machine runs one instruction for each.\n\nModule 9's machine writes R2, -184, at the load's WRITE edge. By then its PC is at `014`, so it fetches the stop next and skips the four instructions between. R3 stays X on Module 9's machine, and its display shows 0, where Module 8's shows -250.\n\nBoth machines halt on the stop at `014`. Module 9's PC has moved on to `01C` by then.\n\nAll 37 of Module 8's programs differ with this fault.",
  explanation:
    "The machine's **instruction set** lists the instructions it runs, each with a word's layout and what it does to parts a program can see. Those parts are R0 to R15, the PC, the memory and the devices. Programs are written for the instruction set.\n\nEvery machine that runs the course's programs must agree on those parts after every instruction. The agreement says nothing about the edges inside an instruction, nor about a circuit's own parts.\n\nThe timer counts instructions, not edges, so both machines read the same count after every instruction.\n\nA **microarchitecture** is a circuit that runs an instruction set: one edge an instruction or several, one or two memory ports, held words or not. Module 8's machine and Module 9's are two microarchitectures of one instruction set.\n\nThe test for a fault: does a wrong word reach a part a program can see? HOLDR stuck at 1 puts words only into HR, which no program sees. The agreement holds. PCEN stuck at 1 moves the PC. HOLDR stuck at 0 leaves HR unwritten. Module 9's state goes to X after the first load's MEMORY edge, and 29 of the 37 programs differ.",
  generalisation:
    "A third circuit could take fewer edges for some kinds. In Module 9's machine a register job takes 4 edges. At ALU, HR takes the ALU's result. At WRITE, register Y takes HR.\n\nThe ALU's result is ready at the ALU edge. So register Y could take it there, and the job would end at that edge, in 3 edges. Every program would run to the same result. The instruction set would not change.\n\nPrograms written for the instruction set run on any microarchitecture of it. A circuit's makers can make it faster without asking anyone to change a program. The challenge asks you to write that circuit.",
  writeShortJobsLead: "Change Module 9's machine so its register and constant jobs take 3 edges.",
  c2Task:
    "Edit the text of Module 9's whole machine, the course's, without the call through a register: the module `machine`, the controller and the decoder. It uses the course's modules for the register file, the ALU, the condition, the memory and the stop logic.\n\nMake the register jobs and constant jobs write register Y at the ALU edge and end there: FETCH, READ, ALU, 3 edges. Every other kind keeps its edges. Three lines change:\n\n- in the controller's next-state logic, the arm for ALU: a job no longer goes to WRITE;\n- the controller's WREG: also 1 at ALU, for an instruction that writes register Y and does not use the memory;\n- in the module `machine`, the word register Y takes: the ALU's result, `RESULT`, where it was `HR`.\n\nThe memory holds one program, run three times from a reset, the shop's signals choosing the path. First, with both signals at 0, the margin program: the tests check the state and the PC after every edge, then HALT and the display, 66, at the stop. Second, with DOOR at 1, a load into R3 from `404`, which the memory refuses at its memory edge: HALT is 1 and CAUSE is 33. Third, with WARM at 1, R3 is stored to the display: the registers keep their words through a reset, so the display shows 66 only if the refused load wrote nothing.\n\nThere are 73 tests. The start fails 48 of them. The first failure is \"Margin: 004, edge 3 (ALU): FETCH after it, PC 008\".",
  c2Hints: [
    "A job's result is ready at the ALU edge. Write it there, and let that edge end the instruction.",
    "A common mistake: changing only the next-state logic. The jobs then take 3 edges but write nothing. R6 stays unknown, and the branch at `008` cannot tell where to go.",
    "A smaller example, the arm for ALU in the next-state logic:\n\n```\nALU: begin if (MEM) next = MEMORY; else next = FETCH; end\n```",
    "Part of the answer, WREG, with `~MEM` so a load's ALU edge writes nothing:\n\n```\nassign WREG = ((state == WRITE) | ((state == ALU) & ~MEM)) & WRITEY & GO;\n```",
    "The whole answer: the arm in hint 3, WREG in hint 4, and in the module `machine` the line `YIN = HR;` becomes `YIN = RESULT;`.",
  ],
  reflection:
    "The instruction set is the agreement. A microarchitecture is one circuit that runs it. Your third circuit ran the tests' program to the same results as Module 9's.\n\nThe agreement covers what each instruction does, and how each instruction's word is laid out. The layout has fields K, J, A, B, Y and three digits of constant. Each field keeps one place in every instruction.\n\nWhy does every field keep one place in every instruction, and what does that cost?",
  modelVsReality:
    "The figures compare the two machines with each other, after every instruction. The course's tests compare Module 9's machine with a model of the machine that runs one instruction at a time, on Module 8's 37 programs. Makers of real machines test a new circuit the same way: against such a model, on many programs.\n\nA maker may sell a small, slow circuit and a large, fast one that run the same programs. How long an instruction takes is not part of the agreement, on the course's machines or on real ones.",
} as const;
