// Copyright © 2026 Christopher Snow

// The words of the lesson interrupts.
//
// Drafted by the course's prose process from briefs of checked facts
// (docs/notes/module-12-traps/briefs, briefs 5A to 5C), checked against the simulator, and
// placed here by the lesson's structure. Edit a fact here only after checking it; the lesson's
// facts test holds the numbers.

export const PROSE = {
  question:
    'Lesson 4 ended on a question. How can the machine go to the handler when the door opens, between two instructions of a program that knows nothing of the door?\n\nThe shop\'s rule: when the freezer\'s door opens, it must close again soon, or ALARM lights.\n\nThe figure runs lesson 4\'s handler with a user program that counts to 30, shows 30 and ends. The door opens while it counts.\n\nThe debugger shows a new panel, "The timer and the door". It shows the timer\'s count, whether "Timer reached 0" and "Door opened" are yes or no, and DOOR and WARM.',
  unseenLead: 'Press "Run to the end" and watch the panel "The timer and the door".',
  unseenAfter:
    'The program shows 30 and ends. The handler\'s `stop` for job 4 ends the run at `054`, after 92 instructions. The panel shows "Door opened: yes".\n\n"waiting" is the word at `7F0`. It has one bit for each event: bit 0 for the timer, bit 1 for the door. The door opened after 15 instructions. Its bit was set at the edge that ended the 16th, the first instruction to run with the door open. Nothing cleared it, so bit 1 is still set.\n\nNo line of the program or the handler read the door. In user mode the program cannot touch a device, and the handler runs only when the program traps.',
  motivation:
    "The machine can go to the handler without the program asking. At the edge that would run the next instruction, if a bit of \"waiting\" is set and C0's bit 1 is 1, the machine traps instead.\n\nA trap that an event outside the program makes, between two of its instructions, is called an **interrupt**. C0's bit 1 says whether interrupts are on.\n\nThe cause says which event. `81` means the timer reached 0, and `82` means the door opened. If both bits are set, the two causes come at one edge, and the lower number wins: `81` goes first.\n\nThe interrupt's edge makes the five transfers every trap makes: C2, C1, C0, C3 and the PC. C0 takes `01`, so interrupts are off in the handler.\n\nThe handler clears an event's bit by storing 1 to it. Storing 1 to `waiting` clears the timer's bit, and storing 2 clears the door's. For the door, the handler sets `R8 <= 2`, then stores it with `word[waiting] <= R8`.\n\nThe start turns interrupts on for the program by writing 2 to C1 instead of 0. C1 is then `10`: bit 1 on, bit 0 off, user mode. `resume` then does what lesson 1 said: the PC takes C2, and C0 takes C1.\n\nInterrupts are taken in user mode and in system mode alike, whenever C0's bit 1 is 1.",
  prediction:
    'The figure lists a new start and a new handler. The start writes 2 to C1, so the program runs with interrupts on. The handler has a part for the door, `door:`, and a part for the timer, `tick:`. This lesson follows the timer\'s part next.\n\nThe user program is the same. The door opens once 15 instructions have run. The interrupt comes while the program is in its loop, between `R2 <= R2 + 1` at `0AC` and `if R2 != R3 goto loop` at `0B0`.\n\nChoose an answer and press "Check my prediction".',
  p1Question: "Just after the door's interrupt, what does C2 hold?",
  p1Explain:
    "C2 holds `0B0`: the branch, the instruction that has not run yet.\n\n`0AC` ran before the interrupt, so going back to it would add 1 to R2 twice.\n\n`0B4` would skip the branch. `01C` is the handler's address, which the PC takes.\n\nAfter `resume`, the branch runs as if nothing had happened: the program never knows.",
  investigation:
    "The timeline runs the program with the new handler and the door opening once 15 instructions have run. It starts at edge 16.\n\nAfter each edge it says the mode and whether interrupts are on.",
  timelineLead:
    "1. Press \"Next edge\" to the door's interrupt, and read its five transfers.\n2. Press \"Next edge\" through the handler's door part to `resume`, and watch where the PC goes.\n3. Press \"Next edge\" on to the timer's interrupt, and through the timer's part.\n4. Press \"Run to the end\".\n\nThe drawing sits beside the list of edges on a wide screen, and above it on a narrow one. It begins with the start's run already made: its first arrow is the start's `resume`, into the program. A bar is the solid strip down a lane, one for each stretch of edges the run spends in that lane. The program's first bar covers its edges 8 to 15, and the list of edges starts at edge 16. Three lanes show the start, the handler and the program. The band for the mode sits beside them, and a second band, new on this page, shows where interrupts are on. A circle in the program's lane marks where the door opens, between two instructions, and another marks where the timer reaches 0. Each interrupt is an arrow to the handler, labelled with C2 and C3; the program's lane stops there and goes on after `resume`.",
  timelineAfter:
    "The door's interrupt came at edge 17, before the branch at `0B0`. The handler cleared the door's bit and set the timer to 20. `resume` took the program back to `0B0`. The timer's interrupt came at edge 47. DOOR was still 1, so the handler lit ALARM. The program showed 30, and job 4 ended the run. The run had 4 traps in all, 2 of them interrupts. The program ran every one of its lines, in order.",
  construction:
    'Whether the next edge takes an interrupt depends only on C0\'s bit 1 and the bits of "waiting". You can work it out without running anything.',
  answersLead: "Work out each answer, then run the tests.",
  c1Task:
    '1. For each case, give the cause the next edge traps with, in hexadecimal, or 0 if the next instruction runs. The instruction itself would not fault.\n2. C0 and "waiting" are written as their two bits, bit 1 first: in C0, bit 1 is interrupts and bit 0 the mode; in "waiting", bit 1 is the door and bit 0 the timer.\n   - C0 is `10` and "waiting" is `10`;\n   - C0 is `00` and "waiting" is `10`;\n   - C0 is `10` and "waiting" is `11`;\n   - C0 is `01` and "waiting" is `01`.\n3. There are 4 tests, one for each case.',
  c1Hints: [
    'The idea: the next edge traps only when C0\'s bit 1 is 1 and a bit of "waiting" is set.',
    "A common mistake: reading C0's bit 0. Bit 0 is the mode; interrupts are bit 1, the left digit.",
    "A smaller example: with C0 at `11` and \"waiting\" at `01`, the next edge traps with cause `81`. C0's bit 1 is 1, so interrupts are on, in system mode as in user mode, and the timer's bit is set.",
    "Part of the answer: when both events wait, the timer's `81` goes first.",
    "The whole answer: `82`, 0, `81` and 0.",
  ],
  failureExperiment:
    "The figure runs the same program with a handler whose door part does not clear the door's bit.\n\nThe door opens once 15 instructions have run.",
  noClearLead: 'Predict how the run ends, then press "Run to the end".',
  noClearAfter:
    "The debugger cut the run off after 5000 instructions. After the door's interrupt, all of them were the handler's, and 384 traps went to the handler.\n\nR2 stays at 4, and the display shows 0.\n\nThe door part never clears the door's bit, so the bit stays set. `resume` takes the PC back to `0B0`, and the edge after each `resume` traps again, with cause `82`, before `0B0` runs.\n\nEach visit sets the timer to 20 again, so the timer never reaches 0, and ALARM never lights.\n\nA handler must clear the event it answers.",
  explanation:
    "There are three ways into the handler.\n\n| What makes it | Its cause | Its return point |\n| --- | --- | --- |\n| A fault: the instruction the machine refuses | `11` to `34` | The instruction that faulted |\n| A system call: `call system` | `41` | The next instruction |\n| An interrupt: an event, with interrupts on | `81` or `82` | The instruction not yet run |\n\nAn interrupt comes between two instructions, never inside one. The instruction before it has finished. The one after it has not started. So the program's registers and memory are as the last edge left them, and `resume` carries on as if nothing had happened.\n\nThe handler must leave the program's registers as it found them, as lesson 2 showed. The handler in this figure saves R8 and R9, and puts them back.\n\nThe handler clears the bit of the event it answers. An event that waits while interrupts are off is not lost. Its bit stays set until the handler clears it.\n\nThe figure runs the program in the debugger, with a breakpoint on each event's part. It lets you choose when the door opens.",
  debuggerLead:
    '1. Choose "after 5 instructions" with "When the door opens".\n2. Press "Run to a breakpoint". The run pauses at the door\'s part.\n3. Read C2 and C3. C3 is `82`. C2 is `0A4`, the program\'s first line, not yet run.\n4. Say why: the door opened while the start ran, with interrupts off (C0 `01`). The door\'s bit waited in "waiting". `resume` turned interrupts on, with C0 taking C1\'s `10`. The next edge took the door\'s interrupt before the program\'s first line ran.\n5. Press "Run to a breakpoint" at each later pause. Read the panel "The timer and the door".\n6. When the button reads "Run to the end", press it. Then try another choice.',
  debuggerAfter:
    'If the door opens after 5, 15 or 50 instructions, the display shows 30, ALARM is on, 132 instructions run and 4 traps go to the handler. With "never", no interrupt comes. 101 instructions run and 2 traps go to the handler: the two `call system`. ALARM stays off.',
  generalisation:
    "An interrupt lets the machine answer an event at once, without the program checking for it. A program that checked the door itself would have to read it again and again, and a user program may not read it at all.\n\nThe start chooses whether the program may be interrupted, by C1's bit 1.\n\nEach event has its bit and its cause. The handler tells them apart by C3, as it tells a fault from a system call.\n\nThe timer is how a handler waits without stopping the program. It sets a count and answers when the count reaches 0.",
  timerLead:
    "Write the timer's part, step through it with the door at different times, then run the tests.",
  c2Task:
    "1. The starting text holds the start and the whole handler, except the timer's part, which only goes to `back`. The start lights the lamps that a word in each test's lines gives, named `startLamps`, before the program runs. Some tests start with ALARM already lit.\n2. Write the timer's part at `tick:`. It clears the timer's bit of \"waiting\", bit 0. Then, if the door is still open, it lights ALARM and leaves the other lamps as they are. If the door has closed, it leaves the lamps alone. Either way it ends by going to `back`.\n3. The door is bit 0 of the word at `7D0`, which the assembler names `signals`. Bit 1 is WARM. The lamps can be read as well as written, with `word[lamps]`.\n4. Two words for bits: `R8 <= R8 & R9` keeps only the bits set in both. `R8 <= R8 | R9` sets every bit set in either. Write each in the form shown, with registers. The assembler does not take the words AND and OR.\n5. An interrupt may change no register, because the program did not ask for it. The timer's part may write R8 and R9. The handler saves them at its start and puts them back at `back`.\n6. There are 5 tests. Each adds a program after yours, named `program`. The program puts a word of its own in R0, R1 and R5 to R15. It counts to 30 in R2 over 30 rounds, and R3 counts the rounds down to R4's 0. It stores R1 in the word at `500`. Then it shows R2 with job 1 and ends with job 4.\n7. Each test opens the door at its own time: left open; closed in time; never opened; opened late and left open; left open on a warm night, with WARM 1.\n8. Each test checks:\n   - the lamps;\n   - the display, which shows 30;\n   - the word at `500`, R1 as the interrupts left it;\n   - R0 and R2 to R15 as the program left them at its last trap, the `call system` for job 4;\n   - the causes, in order;\n   - that the run ends at the handler's `stop` for job 4.",
  c2Hints: [
    'The idea: clear bit 0 of "waiting" by storing 1 to it. Read `signals`, keep bit 0 with `&`, and compare the result with 1. To light ALARM beside the other lamps, read the lamps, set bit 0 with `|`, and store them back.',
    "A common mistake: storing 1 to the lamps. That lights ALARM but puts NIGHT out. Another is comparing all of `signals` with 1: on a warm night WARM's bit is set too, and the comparison fails.",
    "A smaller example: to put ALARM out and leave the other lamps as they are, a part would read `word[lamps]`, `&` it with 6, and store the result back.",
    "Part of the answer: the part starts as the figures' timer part does: `R8 <= 1`, `word[waiting] <= R8`, `R8 <= word[signals]`, `R9 <= 1`, `R8 <= R8 & R9`, then `if R8 != R9 goto back`.",
    "The whole answer:\n\n```\ntick:   R8 <= 1\n        word[waiting] <= R8     // the timer's event is seen\n        R8 <= word[signals]\n        R9 <= 1\n        R8 <= R8 & R9           // DOOR\n        if R8 != R9 goto back   // closed in time\n        R8 <= word[lamps]\n        R8 <= R8 | R9           // ALARM, beside the lamps already lit\n        word[lamps] <= R8\n        goto back\n```",
  ],
  reflection:
    "Every trap's edge turns interrupts off, so a door that opens while the handler runs waits until `resume`. A handler that runs a long job keeps the door waiting for all that time. A handler can also fault, like any program. What happens if a trap comes while the handler runs?",
  modelVsReality:
    "Real machines take interrupts between instructions, as this one does, from many devices: disks, networks, keyboards, timers. Many give each device a number and a table of handler addresses, and let some devices interrupt others. A real timer counts time, not instructions. This machine's timer counts instructions, so every run with the same door is the same.",
} as const;
