// Copyright © 2026 Christopher Snow

// The words of the lesson log-report, the module's capstone.
//
// Drafted by the course's prose process from briefs of checked facts
// (docs/notes/module-11-programming/briefs, briefs 7A to 7C, then 7R2 after the reading review), checked against the simulator, and
// placed here by the lesson's structure. Edit a fact here only after checking it; the lesson's
// facts test holds the numbers.

export const PROSE = {
  question:
    "Lesson 6 ended on a question: can you write a program the shop can use?\n\nThe office wants a report on each day's log. The report shows how many readings are warmer than the limit, on the display. ALARM comes on when any reading is warmer. The day's lowest and highest readings go in the RAM at `400` and `408`, where the office's computer reads them each morning.\n\nThe figure runs the outline, the program the challenge starts from, on six logs. Beside each run, it shows the report that log asks for.",
  asksLead:
    'Press "Run all" to run the outline on each log, and compare what it leaves with what each log asks for.',
  asksAfter:
    "- On every log, the outline shows 0 on the display and turns no lamp on. The words at `400` and `408` show X, because nothing has set them.\n- In the outline, `report` is two lines. Its result is 0, and it calls nothing and stores nothing.\n- The display and the lamps are right only for logs 2, 4 and 6, which ask for 0. No log's report is right as a whole.",
  motivation:
    "The tests check the report like this:\n\n- The display shows how many readings are warmer than the limit. A reading equal to the limit is not warmer.\n- ALARM is on when any reading is warmer. Otherwise no lamp is on.\n- The word at `400` holds the lowest reading, and the word at `408` holds the highest. Both are 0 for an empty log.\n- The program ends at its `stop`.\n\nThe tests add `count`, `limit` and `log` after your program.\n\nFour functions do the work: `report`, and the three it calls, `lowestOf`, `highestOf` and `warmCount`.\n\n`lowestOf` takes the list's address in R1 and how many readings in R2. Its result in R1 is the lowest reading, or 0 for an empty list. `highestOf` takes the same two inputs and gives the highest reading in the same way. `warmCount` also takes the limit in R3, and its result in R1 is how many readings are warmer than the limit. `report` takes the same three inputs, and its result in R1 is also how many readings are warmer than the limit. It stores the lowest reading at `400` and the highest at `408`.\n\nThe tests call each function alone, as in lessons 3 to 5, and run the whole program on each log.",
  prediction:
    "The figure lists a short program. It puts log 5's address in R1, and the log's count, 5, in R2. Then it calls `lowestOf` and shows the result on the display. Log 5's readings are -184, 35, -176, 12 and -190.\n\nThe question asks what R2 holds once `lowestOf` has returned. Choose an answer and press \"Check my prediction\". The listing then shows each line's word.",
  p1Question: "What does R2 hold once `lowestOf` has returned?",
  p1Explain:
    "R2 holds 0. `lowestOf` takes 1 off R2 each time it moves to the next reading. It returns when R2 reaches 0, and its result in R1 is -190.\n\nA called function may change R1 to R9, and `lowestOf` changes R2.\n\nSo `report` must keep the count where a call does not change it. It needs the count again for `highestOf` and `warmCount`. It keeps the count in R11, and it pushes R11's own word first.",
  investigation:
    "The figure runs the program from the prediction with a breakpoint on `lowNext`. It watches R5, the lowest so far, R6, the reading just loaded, and R2. It shows the log.",
  walkLead:
    'Press "Run to a breakpoint" again and again. At each pause, say what R5 and R2 should hold before you look.',
  walkAfter:
    "The run on the model:\n\n- There are 5 pauses. R2 is 5, 4, 3, 2 and 1 at them: it goes down by 1 each time round.\n- R5 is -184 at the first four pauses. The readings in R6 there, 35, -176 and 12, are not lower.\n- At the fifth pause, R6 holds -190, and R5 has taken it.\n- After the fifth pause, R2 reaches 0, `lowestOf` returns with -190 in R1, and the display shows -190. 35 instructions run.",
  construction:
    "- The main program: `R14 <= 0x7C0`, `R1 <= log`, `R2 <= word[count]`, `R3 <= word[limit]` and `call report, R15`. It then stores R1 to the display. If R1 is not 0, it stores 1 to the lamps, where bit 0 is ALARM. It ends with `stop`. It sets R14 first because `report` pushes words (lesson 4).\n- `report`: it pushes R15, R10, R11 and R12 when it starts. It copies R1, R2 and R3 into R10, R11 and R12. It calls `lowestOf` and stores R1 with `word[0x400] <= R1`. It copies R10 and R11 back into R1 and R2, calls `highestOf`, and stores R1 with `word[0x408] <= R1`. It copies R10, R11 and R12 back into R1, R2 and R3 and calls `warmCount`, whose result is already in R1. It pops R12, R11, R10 and R15, in that order, and then runs `goto R15`.\n- `highestOf` is `lowestOf` with one comparison turned round.\n- `warmCount` walks the list as lesson 2's counting program did, with the limit in R3.\n- `lowestOf`, `highestOf` and `warmCount` call nothing and change none of R10 to R14, so they push nothing. Each returns with `goto R15`.\n- Write the addresses as `0x400` and `0x408`. Without `0x`, a number is decimal, and `word[400]` is address 400 decimal, in the ROM, where a store halts with cause `34`.",
  failureExperiment:
    "The figure runs a whole report whose `highestOf` starts its highest so far at 0, not at the first reading. Before you run it, predict which logs it gets wrong.",
  fromZeroLead: 'Press "Run all" and compare the word at `408` with what each log asks for.',
  fromZeroAfter:
    "- It leaves 0 at `408` for logs 1, 2, 3 and 6. Every reading in those logs is below 0, so none is higher than 0.\n- It is right for log 4, the empty log, and for log 5, whose highest is 35.\n- A start of 0 is a guess at the answer. Start from the first reading, as `lowestOf` does.",
  explanation:
    "The report uses lessons 1 to 6 of this module:\n\n- Lesson 1: the log is `word` data that the assembler puts after the program.\n- Lesson 2: each function walks a list with an address register and a count.\n- Lesson 3: the functions take arguments and give results by the calling convention, so the tests can call each one alone.\n- Lesson 4: `report` calls, so it pushes R15. It keeps the address, the count and the limit in R10 to R12 through its calls, and it pushes their own words first. The main program sets R14.\n- Lesson 5: there is no recursion. In a log, each reading leads only one way on, to the next, so a loop does the job.\n- Lesson 6: the tests' logs reach the edges: an empty log, one reading, readings of both signs, and a reading equal to the limit.",
  generalisation:
    "Getting the right answer on one log is not enough. A program the shop can rely on passes tests chosen to reach every edge.\n\nEach function, tested alone, can be used again. Next week's report on room B's log calls the same `lowestOf`.",
  challenge:
    'There are three ways in. The tests are the same for each.\n\n- Guided: the challenge starts from the outline, with the main program and `lowestOf` whole. You write `report`, `highestOf` and `warmCount`. The hints help you one step at a time.\n- From the specification: press "Start from an empty program" and follow the construction\'s specification.\n- From the requirements alone: start from an empty program and use only the task and the tests.',
  reportLead:
    "Choose your way in, write the program, try each function on its own call test in the debugger, then run the tests.",
  c1Task:
    "1. Write a program that reports on the log the tests add after it (`count`, `limit` and `log`). The report:\n   - the display shows how many readings are warmer than the limit, and a reading equal to the limit is not warmer;\n   - ALARM is on when any reading is warmer, and no lamp is on otherwise;\n   - the word at `400` holds the lowest reading and the word at `408` the highest, both 0 for an empty log;\n   - the program ends at its `stop`.\n2. The office's computer reads the words at `400` and `408` each morning. In a program, write them as `0x400` and `0x408`.\n3. Do the work with four functions. `report` is the function the main program calls. `lowestOf`, `highestOf` and `warmCount` are the three that `report` calls. Each takes the list's address in R1 and how many readings are in R2. `report` and `warmCount` also take the limit in R3. Each gives its result in R1. `report` stores the lowest reading at `0x400` and the highest at `0x408`, and its result is how many readings are warmer than the limit. Each keeps the calling convention: R10 to R14 as they were, and a return through R15.\n4. There are 18 tests. Six run the whole program, one on each log. They check the display, the lamps, the words at `400` and `408`, and that the program ends at its `stop`.\n5. Twelve tests call each of the four functions alone, on logs 1, 4 and 5. Before each call, the test puts its own words in R10 to R13, `7C0` in R14, and, in R15, the address of a `stop` that it adds after your program. The call returns to that `stop`. Each test checks R1, R10 to R14, and the return through R15. The tests that call `report` also check the words at `400` and `408`, that 3 calls returned, and that the stack held at least 1 word.\n6. \"Run with\" lists every test, the calls too, so you can run one in the debugger.\n7. The six logs, each with its limit:\n   - Log 1: -184, -190, -176, -181, -172, -188. Limit -180.\n   - Log 2: -195, -200, -191, -199. Limit -180.\n   - Log 3: -175. Limit -180.\n   - Log 4: empty. Limit -180.\n   - Log 5: -184, 35, -176, 12, -190. Limit -180.\n   - Log 6: -150, -160, -155. Limit -150.",
  c1Hints: [
    'The idea: write one function at a time. Run its call test from "Run with" in the debugger before you write the next. The functions you have not written yet can stay as the outline\'s two lines.',
    "A common mistake: calling `highestOf` with R2 as `lowestOf` left it. `lowestOf` leaves R2 at 0, so `highestOf` sees an empty list and returns with 0 in R1. `report` must keep the count in R11, and put it back in R2 before each call.",
    "A smaller example: lesson 4's `sumOver` pushed R15 and R10 when it started, and popped R10, then R15, before `goto R15`. `report` does the same with R15, R10, R11 and R12, popping them in the opposite order.",
    "Part of the answer: `highestOf` is `lowestOf` with `if R6 < R5 signed goto highNext` in place of `if R5 < R6 signed goto lowNext`, and its own names. `warmCount` counts with `if R3 >= R6 signed goto warmSkip`.",
    "The whole answer: replace the outline's `report`, `highestOf` and `warmCount` with the code below, exactly as given:\n\n```\nreport:   R14 <= R14 - 8\n          word[R14] <= R15\n          R14 <= R14 - 8\n          word[R14] <= R10\n          R14 <= R14 - 8\n          word[R14] <= R11\n          R14 <= R14 - 8\n          word[R14] <= R12\n          R10 <= R1\n          R11 <= R2\n          R12 <= R3\n          call lowestOf, R15\n          word[0x400] <= R1\n          R1 <= R10\n          R2 <= R11\n          call highestOf, R15\n          word[0x408] <= R1\n          R1 <= R10\n          R2 <= R11\n          R3 <= R12\n          call warmCount, R15\n          R12 <= word[R14]\n          R14 <= R14 + 8\n          R11 <= word[R14]\n          R14 <= R14 + 8\n          R10 <= word[R14]\n          R14 <= R14 + 8\n          R15 <= word[R14]\n          R14 <= R14 + 8\n          goto R15\n\nhighestOf: R0 <= 0\n          if R2 == R0 goto highNone\n          R5 <= word[R1]\nhighNext: R1 <= R1 + 8\n          R2 <= R2 - 1\n          if R2 == R0 goto highDone\n          R6 <= word[R1]\n          if R6 < R5 signed goto highNext\n          R5 <= R6\n          goto highNext\nhighDone: R1 <= R5\n          goto R15\nhighNone: R1 <= 0\n          goto R15\n\nwarmCount: R0 <= 0\n          R5 <= 0\nwarmNext: if R2 == R0 goto warmDone\n          R6 <= word[R1]\n          if R3 >= R6 signed goto warmSkip\n          R5 <= R5 + 1\nwarmSkip: R1 <= R1 + 8\n          R2 <= R2 - 1\n          goto warmNext\nwarmDone: R1 <= R5\n          goto R15\n```",
  ],
  reflection:
    "Your program reaches the display and the lamps itself, with stores.\n\nWhen a program does something the machine refuses, the machine halts and nothing more runs.\n\nA shop's machine runs more than one program. One program's mistake should not end them all.\n\nWhat if, instead of halting, the machine went to a program of its own, said why, and carried on?",
  modelVsReality:
    "A real program would read the day's log from storage that keeps it, not from data added after the program. The tests add the log so every log can be tried without changing the program.\n\nReal programs are tested the same way: on chosen inputs, and with each function called alone.\n\nTests can only show the mistakes their inputs reach.",
} as const;
