// Copyright © 2026 Chris Snow

// The words of the lesson on signals and bits.
//
// Drafted by the course's prose process from briefs of checked facts (see CLAUDE.md and
// docs/notes/module-1-signals.md) and checked against the model, then placed here by the
// lesson's structure in signals.ts. Edit a fact here only after checking it; the lesson's
// facts test (signals.facts.test.ts) holds the numbers.

export const PROSE = {
  question:
    "A temperature sensor in a shop's freezer room sends the temperature to a display in the shop's office along a cable 30 metres long. The sensor counts in tenths of a degree Celsius. The freezer room is at -18.4 degrees Celsius, so the sensor sends -184. The cable runs past the freezer room's compressor motor. The sensor sends the temperature as 16 steps, one after another. A step is a short, fixed length of time. The display expects 16 steps, so the sensor always sends 16 steps however large or small the temperature. In each step it drives the cable to 0 V for a 0, or to 3.30 V for a 1.",
  questionAfter:
    "The receiver in the display measures the cable's voltage once in each step. Each such measurement is a **sample**. So one temperature arrives as 16 samples, one for each step. But the samples never come back as exactly 0 V or 3.30 V. Noise from the cable and the motor moves each sample away from what the sensor sent.\n\nThe display must turn these wobbling voltages into clean 0s and 1s. Then it must read those 16 0s and 1s as a temperature. How does it do both?",
  motivation:
    "The sensor drives the cable to only two voltages: 0 V and 3.30 V, far apart. The receiver does not need the exact voltage. It only needs to tell which one the sensor meant.\n\nA small wobble does no harm. It does harm only when it carries a sample far enough that it looks like the other voltage.\n\nOnce the receiver has decided each sample is a 0 or a 1, the noise is gone. The display keeps a clean 0 or 1, not the wobbly voltage. Getting all 16 of these 0s and 1s right is not the whole job. The display must also turn them into a temperature, and that needs a rule the sensor and the display agree on.",
  prediction:
    'The receiver decides each sample by comparing it with one voltage. A sample at or above that voltage comes out as 1; below it comes out as 0. That voltage is the **threshold**.\n\nThe figure below asks which of two thresholds causes fewer samples to come out wrong. Before you answer, it shows one plot: the 16 samples with the compressor running, each a dot at its voltage, with no threshold drawn. The 16 samples are a recording: they were made in advance by the course\'s program, called the model. They were not measured on a real cable. Choose an answer, then press "Check my prediction". Then the figure shows two plots, one for each threshold, with each sample marked by how it came out. The answer comes from the model.',
  p1Question:
    "The compressor is running. One receiver uses a threshold of 2.40 V, close to 3.30 V. Another uses 1.40 V, closer to the middle than 2.40 V. Which threshold causes fewer samples to come out wrong?",
  p1Explain:
    "At 2.40 V, 3 samples come out wrong: samples 5, 6 and 13. All three were sent as 1, but the noise pulled each below 2.40 V. At 1.40 V, none comes out wrong. A threshold close to 3.30 V leaves little room on that side. The noise needs to move a sample only a little to carry it across.",
  exploreSignalLead:
    "The figure shows 16 samples from the cable's voltage. Each sample is a dot on the graph. A horizontal line marks the threshold, with dashed lines at 0 V and 3.30 V where the sensor drives the cable. A thin line joins each dot to the voltage the sensor sent in that step: 0 V or 3.30 V. The line's length shows how far the noise moved that sample. Below the plot are rows for each sample's number, what was sent (0 or 1), and what the receiver received. A filled dot means a 1 came out; a hollow dot means 0. A sample that comes out wrong has a ring round it.\n\nWhen a sample arrives, it comes out as 0 or 1. That 0 or 1 is a **bit**.\n\nThe figure starts at 2.40 V with the compressor off. Every sample comes out as sent. Choose the recording with the compressor running: the noise from the motor moves samples, and the same threshold now makes 3 samples come out wrong.\n\nMove the threshold slider down. Watch the lines below the plot: they show the highest sample sent as 0 and the lowest sent as 1, each with how far it is from the threshold. When a sample is on the wrong side of the threshold, the line says so.",
  exploreSignalAfter:
    "Every sample comes out as sent when the threshold sits between the highest sample sent as 0 and the lowest sent as 1. The gap between the threshold and the nearest sample on each side is how much more noise that sample could take before it comes out wrong. That gap is the **noise margin**.\n\nWith the compressor running and the threshold at 1.40 V, every sample comes out as sent, but the highest 0 sample, sample 16, is only 0.29 V below the threshold. A little more noise on that sample would make it come out as 1.\n\nAt 1.70 V the gaps are 0.59 V below (sample 16) and 0.55 V above (sample 5). Moving the threshold widens one gap and narrows the other. Near the middle of the two voltages, both gaps are reasonably wide.",
  construction:
    "The receiver needs one threshold that works for both recordings: with the compressor off and with it running, with wide noise margins on both sides. First you choose the threshold. Then you turn the 16 received bits into a number.",
  setThresholdLead: "Try thresholds on both recordings in the figure above.",
  c1Task:
    "Choose one threshold in volts for the receiver. The tests check both recordings with it.\n\nFor each recording, every sample must come out as it was sent. The noise margin must be at least 0.30 V on both sides: the highest sample sent as 0 at least 0.30 V below the threshold, and the lowest sent as 1 at least 0.30 V above it.\n\nThere are 4 tests: two recordings, each checked for wrong samples and for the noise margin.",
  predictSumLead:
    'The display receives 16 bits from the sensor: `1111 1111 0100 1000`. The sensor and the display agree on their order: step 1 carries bit 15, the top bit, written leftmost; step 16 carries bit 0, written rightmost. Writing a number with only 0s and 1s, each place worth twice the one to its right, is **binary**. A fixed number of bits taken together is a **word**: here, 16 of them.\n\nThe sensor sent -184. Work out what the display gets when it adds the worths of the 1s. Choose an answer, then press "Check my prediction".',
  p3Question: "The display adds the worth of every 1 bit in the word. What does it get?",
  p3Explain:
    "The 1s are worth 32768 + 16384 + 8192 + 4096 + 2048 + 1024 + 512 + 256 + 64 + 8 = 65352.\n\nThe sensor sent -184. The display got 65352. Every bit arrived as the sensor sent it, so the problem is not the threshold.",
  predictSumAfter:
    "Adding the worths of every 1 in the word, each counted as positive, is the **unsigned** reading. 16 bits make 65536 different patterns. Read unsigned, they are the numbers 0 to 65535.",
  breakSignalLead:
    "The figure shows the compressor recording with three new things. A second slider multiplies the noise on every sample by the same amount, from 1.0 to 3.0 times. As you turn it up, each thin line from a dot to the voltage sent grows by that amount and keeps its direction. A shaded band in the plot, behind the dots, shows every threshold where all 16 samples come out as sent. The threshold starts at 1.70 V. At 1.0 times, the band runs from 1.12 V to 2.25 V. A line under the plot gives the sent bits and the received bits, each read unsigned, as two numbers.\n\nMove the noise up 0.1 at a time and watch what happens to the band. At 1.5 times it shrinks to 1.67 V to 1.72 V. At 1.6 times the band vanishes: no threshold lets all 16 come out as sent.",
  breakSignalAfter:
    "At 1.6 times the noise, with the threshold at 1.70 V, samples 5 and 16 come out wrong. Sample 5 carries bit 11, which is worth 2048. The sensor sent a 1, but it came out as 0, so the number loses 2048. Sample 16 carries bit 0, worth 1. The sensor sent a 0, but it came out as 1, so the number gains 1. The result: 65352 - 2048 + 1 = 63305. Each wrong bit changes the number by its worth, down or up.\n\nWhen the noise grows this large, no threshold helps. The answer lies outside the receiver, in one of two ways: less noise on the cable, for example by running the cable away from the motor; or two voltages further apart, so that the gap between them is wider than the noise.",
  explanation:
    "Back to the 65352. Every bit arrived as the sensor sent it. The threshold did its job.\n\nThe display read the word unsigned, so every bit's worth counted as positive. 65352 tenths of a degree is 6535.2 degrees. The sensor measures only from -50.0 to 50.0 degrees, so 6535.2 cannot be the temperature. A temperature outside that range shows the unsigned rule does not work for this word.\n\nThe sensor did not use the unsigned rule. It wrote the number with a different rule for the top bit (bit 15, the leftmost), and the result was -184. Nothing in the 16 bits says which rule was meant. The display had to be told.",
  signedWordLead:
    "The display's word `1111 1111 0100 1000` can be read two ways. The figure shows both. Instead of counting the top bit as worth 32768, count it as worth -32768. The figure labels bit 15 with this worth. Count every other bit as it was. This is the **signed** reading. Read this way, the word is -184: take -32768 and add the worths of the other bits that are 1. The sensor sent -184: its temperature in tenths of a degree, -18.4 degrees. Press any bit to flip it between a 0 and a 1, and both readings update.",
  signedWordAfter:
    "When the top bit is 0, both readings give the same number. The sensor writes every temperature of zero or above with the top bit 0, and every temperature below zero with the top bit 1. So a display that reads the word unsigned shows the right temperature for every temperature of zero or above, and a wrong temperature only below zero.\n\nWhen the top bit is 1, the unsigned reading is always the signed reading plus 65536. Here, 65352 = -184 + 65536. Read as signed, 16 bits are the numbers -32768 to 32767. Read as unsigned, 0 to 65535. Both rules make use of all 65536 different patterns. Neither rule is wrong in itself: each gives the right number, by its own rule, from the same bits.",
  manyReadingsLead:
    "Writing out 16 bits is long and easy to copy wrongly. Take the bits in groups of four from the right. Within each group, the places are worth 8, 4, 2 and 1. `0100` has only 4, so its digit is 4. `1000` is 8. `1111` is 8+4+2+1 = 15, written F. So `1111 1111 0100 1000` is `FF48`. This way of writing bits is called **hexadecimal**. Hexadecimal is a shorter way to write the same bits, not a different number.\n\nThe figure shows one word at a time, read one way at a time. Choose a word and how to read it. The bits do not change when the reading does. Only the rule changes.\n\nYou can also read the same 16 bits another way: send them to a row of 16 lamps, lighting the ones whose bit is 1. That pattern is not a number at all.",
  manyReadingsAfter:
    "The word for 1.8 degrees is `0000 0000 0001 0010`. Read unsigned, it is 18. Read signed, it is also 18, because the top bit is 0. When all 16 bits are 1, you get `1111 1111 1111 1111`, which reads 65535 unsigned and -1 signed. In hexadecimal, that is `FFFF`.\n\nThe course builds a computer that works on 16-bit words. A word inside it, like the one the display received, is a pattern of bits. The part that reads a word must use the rule the word was written with. Nothing in the bits says which rule that is, so the writer and the reader must agree.",
  predictTopLead: "Here is one more prediction. Use the rule for the signed reading.",
  p2Question: "The word is `1000 0000 0000 0000`. Only bit 15 is 1. What does it read as signed?",
  p2Explain:
    "Read signed, bit 15 is worth -32768 and no other bit is 1, so the word is -32768. Read unsigned, the same bits are 32768. It is the most negative number a 16-bit word can be when read signed.",
  freezerWordLead: "The same sensor is moved to a second freezer room, kept colder.",
  c2Task:
    "This second freezer room is at -25.0 degrees. The sensor counts in tenths of a degree, so the word it sends reads as -250 when read signed. Set the 16 bits the sensor sends by pressing each bit to change it. Then type what a display that reads the word unsigned would get, and the word in hexadecimal. There are 3 tests: your bits must read signed as -250, your unsigned answer must be the unsigned reading of your bits, and your hexadecimal answer must match your bits. You can try bits in the explanation figure first.",
  reflection:
    "A receiver turns a wobbling voltage into bits using a threshold. The noise margin on each side is how much more noise can happen before a sample comes out wrong. When the noise carries some 0 sample up to or above some 1 sample, there is no gap left between them. No threshold can make every sample come out as sent.\n\nA word is a pattern of bits. The bits themselves mean nothing. Unsigned, signed and lamps are three ways of reading the same bits for different meanings. Hexadecimal is a shorter way of writing the bits.\n\nTo turn 16 bits into a temperature, the display must be told four things the bits do not carry:\n\n- The step that carries the top bit: step 1.\n- The rule to read the word by: unsigned or signed.\n- The scale of the reading: tenths of a degree.\n- The unit of measurement: degrees Celsius.\n\nSigned and unsigned readings use the same 65536 patterns. Could one way of adding two words serve both readings?",
  modelVsReality:
    "The recordings on this page are made by the course's model from a fixed starting number. They are the same on every visit. Real noise is different every time. The numbers you see are a teaching choice, not a measurement from a real cable.\n\nOn a real cable, the voltage does not jump from one level to the other. It changes over a short time, the way a container fills through a narrow pipe, and passes through the middle on the way. The model takes one sample in the middle of each step, after the voltage has settled. It draws no changes between steps.\n\nMany real receivers use two thresholds: a higher one for a 1 and a lower one for a 0. They promise nothing for a voltage between them. The model uses one threshold.\n\nOn this page, the noise margin is measured after the noise: from the threshold to the nearest recorded sample on each side. A datasheet measures noise margin before any noise: from the voltage a sender promises to drive to the voltage a receiver promises to read correctly.\n\nReal sensors come with a written description of what a display must know to turn the sensor's bits into a temperature. The freezer room in this lesson is invented. The display's fault is a common one in real equipment: reading a sensor's word by a different rule from the one the sensor wrote it with.",
  c1Hints: [
    "Every sample comes out as sent when the threshold is above the highest sample sent as 0 and at or below the lowest sent as 1. The noise margin is the gap to each.",
    "A threshold can make every sample come out as sent but still fail the test if it sits close to one side. For example, 1.40 V makes every sample come out as sent in the compressor recording, but the highest 0 sample is only 0.29 V below it, failing the noise margin test.",
    "With the compressor off, every sample is within 0.18 V of 0 V or 3.30 V, so almost any threshold between them works. The compressor recording is what limits you.",
    "With the compressor running, sample 16 is the highest 0 sample and sample 5 is the lowest 1 sample. The threshold must be at least 0.30 V above sample 16 and at least 0.30 V below sample 5.",
    "Any threshold from 1.45 V to 1.95 V works. Try 1.70 V: it gives gaps of 0.59 V and 0.55 V with the compressor running.",
  ],
  c2Hints: [
    "Read signed, a word whose bit 15 is 1 is -32768 plus the worths of its other 1 bits. So a negative number needs bit 15 set to 1.",
    "Setting the bits for 250 is a common mistake. There is no minus sign in the bits. Bit 15's worth of -32768 is what makes the number negative.",
    "A smaller example: the word `1111 1111 1111 1110` reads -2 when read signed. Read unsigned, the same word is -2 + 65536 = 65534. Its last group, `1110`, is 8 + 4 + 2 = 14, written E. So in hexadecimal the word is `FFFE`.",
    "Bit 15 must be 1 (worth -32768), and the other bits must add up to 32518, because -32768 + 32518 = -250.",
    "The answer is `1111 1111 0000 0110`. Unsigned it is 65286; in hexadecimal, `FF06`.",
  ],
} as const;
