// Copyright © 2026 Christopher Snow

// The words of the lesson system-call-mechanism.
//
// Drafted by the course's prose process from briefs of checked facts
// (docs/notes/module-12-traps/briefs, briefs 8A to 8C), checked against the simulator, and
// placed here by the lesson's structure. Edit a fact here only after checking it; the lesson's
// facts test holds the numbers.

export const PROSE = {
  question:
    "Lesson 7 ended on a question. Can you write the handler that runs the shop's programs, one after another, each in user mode, and gives them the jobs of lesson 4?\n\nThe figure runs the outline, the challenge's starting text, on the 7 runs the tests use. The outline gives the choice of job and jobs 1 to 3. It leaves the start of each program and the end of each to you.",
  asksLead: "Read what each run asks, then press the button and compare what the outline left.",
  asksAfter:
    "The outline's start only stops, so in every run the machine stops after 5 instructions. No program runs: nothing is shown and no record is written. Only run 7, the empty table, matches what its test asks.",
  motivation:
    "The text you write has five parts. The first is the start, which runs from reset. The other four are parts of the handler, the lines at the address C4 holds.\n\n- The start sets C4 to the handler's address. Then it runs the program whose number the word at `480` holds, counting from 0. It finds the program's address in the table `programs`, which the tests add after your text. The table's first word is how many programs there are. Each program's address comes after it. It runs the program in user mode with interrupts off, by writing C1 and C2, then running `resume`.\n- The choice is the handler's first part. It reads C3 to tell a system call from a fault. It reads R1 to find the job.\n- The jobs are these. Job 1 shows R2. Job 2 puts a room's reading in R1. Job 3 sets the lamps from R2's bits 2 to 0. Job 4 ends the program.\n- The end of a program stores its record at `400` plus 8 times its number. Then it moves to the next number and goes back to the start.\n- The stop comes after the last program. It stops the machine.\n\nThe number lives in the RAM, in the word at `480`, because a register is a program's to change. The RAM is not protected either. A user program could store over that word, as lesson 3's program stored over the handler's count. The word at `480` is safe only from the program's registers.\n\nJob 2 checks R2, because lesson 6 taught that a handler must not trust what a program gives it. R2 is 0 for room A and 1 for room B. Any other value puts 0 in R1, so no program can make the handler read a word that is not a sensor.\n\nA job may change R1 and R2 only, the call's own registers, as lesson 4 said. The handler keeps every other register for the program.",
  prediction:
    'The figure lists a handler smaller than the challenge\'s. Its start runs one program, named `program`, in user mode. Its handler writes C3 to the word at `400` as a record, then stops.\n\nThe program loads a word from `404`, an address that is not a multiple of 8.\n\nChoose an answer and press "Check my prediction".',
  p1Question: "When the run stops, what does the word at `400` hold, as the page writes a word?",
  p1Explain:
    "The word at `400` holds 51. The load faults with cause `33`, and the handler stores C3 as a word. C3 holds the cause itself.\n\nA word is written as a decimal number. `33` in hexadecimal is 3 × 16 + 3 = 51.\n\nThe record is not 33. That would be the cause's digits read as a decimal number, and the handler never writes that. The record is not 0 either, because 0 means the program ended with job 4, and this program never reached job 4. Nor is it 52, which is cause `34`, a store the machine refuses.",
  investigation:
    "The debugger runs the prediction's handler and program. It shows R2, R3 and R5, the control registers with the mode spelled out, and the record at `400`, with a breakpoint on the handler's first line.",
  walkLead:
    '1. Press "Step" through the start, to `resume`, and read C0 after it: user mode.\n2. Press "Run to a breakpoint". The run pauses at the handler\'s first line. Read C1, C2 and C3: C1 holds `00`, the program\'s mode, C2 holds `02C`, the load, and C3 holds `33`.\n3. Press "Run to the end", and read the record at `400`.',
  walkAfter:
    "The run stops at the handler's `stop`, after 11 instructions and 1 trap. The record at `400` holds 51 `033`: cause `33` itself, stored as a word.",
  construction:
    "Build the handler from the outline in this order, and run the tests after each step.\n\n1. Write the start: the program number at `480`, its address from the table, C1 and C2, then `resume`; and the stop after the last program. The outline's `finish:` and `ended:` still only stop. Run 1 shows 25, then stops at `finish:`. Run 7 matches.\n2. Write the end of a program for job 4, at `finish:`: record 0, move to the next number, and go back to the start. Runs 1, 4, 6 and 7 match.\n3. Make a fault's end write the cause as the record, with the same lines. Every run matches.\n\nThen use the debugger in the challenge: set breakpoints, and step through any test's programs.",
  failureExperiment:
    "The figure runs a handler whose fault part skips the faulting instruction, as lesson 1's handler did. It adds 4 to C2 and resumes, instead of ending the program. The figure runs it on the 7 runs.",
  skippingLead: "Predict which runs match, then press the button.",
  skippingAfter:
    "Runs 1, 4, 6 and 7 still match their tests. Run 2 does not: the store to the display is skipped, and run 2's first program ends with job 4, so its record is 0, not 50. The display still shows 8.\n\nRun 3 skips the refused `stop`. The run goes on past the program's end, onto words that are not instructions, and each one is skipped in turn. The run is cut off after 5000 instructions. Run 5 has the same result: the word that is not an instruction is skipped, and the run is cut off after 5000 instructions.\n\nSkipping suits a handler that knows what the program meant. A handler that runs programs it did not write cannot know, so it ends the program and records why.",
  explanation:
    "The handler is the only program that runs in system mode. Every user program reaches the display, the sensors and the lamps only through its jobs. Everything user mode refuses comes back to the handler as a trap. A mistake that user mode allows, such as a store into the RAM or a loop that never ends, does not.\n\nA program ends in one of two ways. It asks for job 4, or it faults. Both lead to the same lines: record, next number, start. A fault's record is its cause, stored as a word, so the shop can read why the program ended: cause `32` reads 50. A program that ends with job 4 records 0.\n\nLessons 1 to 6 each gave one part. Lesson 1 gave the trap and `resume`. Lesson 2 gave saving registers. Lesson 3 gave user mode. Lesson 4 gave system calls. Lesson 6 gave the handler's own state, saved in memory, and the rule to trust nothing a program gives it. Interrupts (lesson 5) are off in these runs.",
  generalisation:
    "A handler that runs programs one after another, gives them jobs and ends them when they fault is the core of the program a real machine runs first, which runs all the others.\n\nEverything it needs is on this machine: C0 to C4, `resume`, user mode and `call system`.\n\nWhat it does not do here is share the machine between programs that run at the same time. With the timer's interrupt, a handler could switch away from one program and resume another. That is beyond this module.",
  challenge:
    'There are two ways in, each chosen with the challenge\'s own buttons.\n\n"Start from the outline" gives the challenge\'s starting text: the choice of job and jobs 1 to 3. You write the start of each program and the end of each, as the construction\'s steps say.\n\n"Start from an empty program" gives the requirements as comments. You write all five parts described above yourself.\n\nEither way, the task and the tests are the same.',
  runLead: "Write the handler, step through it on the tests' programs, then run the tests.",
  c1Task:
    "1. Write a handler that runs each program the table `programs` names, in order, in user mode with interrupts off. The tests add the table and the programs after it.\n2. Offer jobs 1 to 4 by `call system`. Job 1 shows R2. Job 2 puts a room's reading in R1: R2 is 0 for room A and 1 for room B. Any other R2 puts 0 in R1. Job 3 sets the lamps from R2's bits 2 to 0. Job 4 ends the program.\n3. A program that faults ends there. For program k, counting from 0, store its record in the word at `400` plus 8 times k. Write it as `word[R1 + 0x400]`, with 8 × k in R1. The record is 0 if the program ended with job 4. If it faulted, the record is its cause itself.\n4. A job may change R1 and R2 only. After the last program, the handler runs `stop`.\n5. There are 7 tests. In them, room A reads -184 and room B reads -250. Each test checks the words shown, the lamps, each program's record, and that the run ends at the handler's `stop`. It also checks C1 at the end: the last program's status at its last trap, `00`. `00` means user mode with interrupts off.\n6. Run 6's second program puts a word of its own in R0 and in each of R3 to R15. Its test also checks those registers as the program left them at its last trap, which is the `call system` for job 4.",
  c1Hints: [
    "The idea: store the number of the program running in the RAM word at `480`. The start reads that word, finds the program's address in the table, writes 0 to C1 and the address to C2, and runs `resume`.",
    "A common mistake: running `stop` for job 4. That stops the machine. Job 4 ends the program, and the handler starts the next one.",
    "A smaller example: a handler that counts every trap it takes stores the count in a RAM word of its own, such as `word[0x488]`, not in a register. A register is the program's to change. Each time, it loads the word, adds 1 and stores it back.",
    "Part of the answer: the program's address is the word at `programs + 8 + 8k`. Multiply k by 8 by adding it to itself three times: each addition doubles it. Add `programs`, then load with `word[R1 + 8]`.",
    "The whole answer: the outline's lines, with these two parts in place of its stubs. The start, in place of `start:  stop`:\n\n```\nstart:  R1 <= word[0x480]       // run program number R1, if there is one\n        R2 <= word[programs]\n        if R1 == R2 goto done\n        R1 <= R1 + R1\n        R1 <= R1 + R1\n        R1 <= R1 + R1           // 8 × R1\n        R2 <= programs\n        R1 <= R1 + R2\n        R1 <= word[R1 + 8]      // its address, from the table\n        C2 <= R1\n        R1 <= 0\n        C1 <= R1                // user mode, interrupts off\n        resume\ndone:   stop\n```\n\nAnd the end of a program, in place of `finish: stop` and `ended:  stop`:\n\n```\nfinish: R9 <= 0                 // job 4: the program ended; its record is 0\nended:  R8 <= word[0x480]       // record R9 for program R8, at 0x400 + 8 × R8\n        R1 <= R8 + R8\n        R1 <= R1 + R1\n        R1 <= R1 + R1\n        word[R1 + 0x400] <= R9\n        R8 <= R8 + 1\n        word[0x480] <= R8       // the next program\n        goto start\n```",
  ],
  reflection:
    "The machine now runs the shop's programs. It has logic gates, registers, a datapath, a controller, an instruction set, programs, and a handler over them.\n\nEvery part was built, but in separate lessons, on separate drawings.\n\nCan you follow one of the shop's programs through the handler and down to the gates of the one machine that runs it?",
  modelVsReality:
    "A real machine's first program does what this handler does, with far more: it loads programs from storage and gives each its own memory. Its jobs are numbered as this handler's are, and a program asks for a job with one instruction.",
} as const;
