// Copyright © 2026 Christopher Snow

// The words of the lesson whole-machine.
//
// Drafted by the course's prose process from briefs of checked facts
// (docs/notes/module-13-machine/briefs, briefs 1A to 1C), checked against the simulator, and
// placed here by the lesson's structure. Edit a fact here only after checking it; the lesson's
// facts test holds the numbers.

export const PROSE = {
  question:
    "Module 12 ended on a question: \"Every part was built, but in separate lessons, on separate drawings. Can you follow one of the shop's programs through the handler and down to the gates of the one machine that runs it?\"\n\nModule 0 asked the same from the top. The machine was a box that ran lines of a program. Its second lesson followed one line down to one wire, on a path chosen for you.\n\nThis module answers the question with the machine whose every part you have now built. Each part was tested in its own lesson. Here the parts run together. This lesson asks which parts make the whole machine, and where they meet.\n\nThe figure below is that machine, running the shop's last program. It is Module 0's first program, written for this machine.",
  makersLead:
    "Open each of the three blocks in turn by pressing it. The table under the drawing names each part at the level on show and the module that built it.",
  makersAfter:
    "The top level has three blocks. The control unit (`control`) was built in Module 9 and grown in Modules 10 and 12. The datapath (`datapath`) was built in Module 8 and grown in Modules 9, 10 and 12. The memory port (`port`) was built in Module 9 and grown in Module 12.\n\nInside the datapath: the register file (Module 6), the ALU (Module 7), the PC (Module 5), the IR (Module 9) and the control registers (Module 12).\n\nInside the control unit: the decoder (Module 9, grown in Module 10), the controller (Module 9, grown in Module 12) and the trap logic (Module 12).\n\nInside the memory port: the memory (Module 6, grown in Modules 8, 9 and 12).",
  motivation:
    "This is the course's final machine: Module 12's machine of several edges, with its trap hardware, and the two instructions you added in your own copy: the call through a register (Module 9) and set if (Module 10).\n\nWhat that took: the decoder that Module 10's capstone built, which knows kind 9 and kind A; and a fourth source for the word register Y takes, MET as a word, 0 or 1, chosen by SET.\n\nThe machine is built from the course's parts. Each passes the tests your own part passed in its lesson. It does not run your own earlier answers: each lesson keeps its own work.\n\nA part's tests checked it alone. The machine also needs its parts joined. A bus or a wire between two blocks, where one block's output becomes another's input, is called a **join**.\n\nThree joins as examples. The control unit sends the control bus, CONTROL, every control signal joined into one bus, to the datapath and to the memory port. The datapath sends the instruction in the IR back to the control unit, which decodes it. The memory port sends FETCHED, the word at the PC, to the datapath, where the IR takes it at a FETCH edge. The challenge asks about the others.\n\nEach wire is driven by one block. Its name is on that block's right side, where its outputs are, and on the left side of each block it enters.\n\nAn instruction's words cross these joins edge by edge. The rest of this lesson follows them.",
  prediction:
    'The figure shows the shop\'s program, stopped after 47 edges. The next edge is the WRITE edge of `call R6, R15`, at `02C`: the call through a register, kind 9.\n\nThe figure shows R6 and R15. No value shows until you commit to an answer.\n\nChoose an answer and press "Check my prediction".',
  p1Question: "What does the PC hold after the next edge?",
  p1Explain:
    'The PC takes `034`, the address of the line `show:`. A call through a register takes R6 plus the constant, and the constant is 0. R6 holds 52, which is `034`.\n\nAt the same edge R15 takes `030`, the PC plus 4: the line after the call, `stop`, where `goto R15` will return.\n\n`02C` is the call itself, and `000` is where the run began.\n\nPress "Next edge" and read the line under the buttons.',
  investigation:
    "The figure is a timing diagram of the shop's program from edge 57 to edge 68. It shows the system call, the handler, `resume` and the return. Each edge keeps its number from the reset.\n\nIts lanes are signals that cross joins. FETCHED runs from the memory port to the datapath. IR runs from the datapath to the control unit. TRAP runs on the control bus to the datapath. CAUSE runs from the control unit to the datapath. ADDR runs from the datapath to the memory port. There are lanes too for S, the controller's state, and for the PC.",
  timelineLead: "Move the cursor edge by edge and find where each value crosses a join.",
  timelineAfter:
    "1. Edge 57 is the FETCH edge of `call system`, at `03C`. ADDR carries the PC, `03C`, to the memory port. FETCHED brings back `80000000`, and the IR takes it at edge 57.\n2. Before edge 58, the control unit has decoded the IR: TRAP is 1 and CAUSE is `41`. Edge 58 is the READ edge. At edge 58 the PC takes `044`, the handler's address, C3 takes `41` and C2 takes `040`.\n3. Edges 59 to 62 run the handler's store, `word[display] <= R2`. At its MEMORY edge, edge 62, ADDR carries `7C0`, the display's address.\n4. At every FETCH edge, ADDR carries the PC. At the other edges it carries HR, the ALU's held result.\n5. Edges 63 to 68 run `resume` and `goto R15`. The challenge asks about them.",
  construction:
    "Follow one load across the joins: `R1 <= word[sensorA]`, at `008`, on edges 8 to 12. The figure starts after edge 7. It shows FETCHING, MLOAD, HOLDM and WREG, the line, its word and R1.\n\n1. Edge 8, FETCH: FETCHING is 1. ADDR carries the PC, `008`. FETCHED brings `380017D8` from the memory port, and the IR takes it.\n2. Edge 9, READ: HA and HB take the values of the registers the instruction names. The control unit has already decoded the IR's word as a load (kind 3), so the controller goes on to ALU.\n3. Edge 10, ALU: the ALU adds 0 and the constant, `7D8`. HR takes `7D8`.\n4. Edge 11, MEMORY: ADDR carries HR, `7D8`, room A's sensor. MQ brings -184 back from the memory port. MLOAD and HOLDM are 1, and HM takes -184.\n5. Edge 12, WRITE: WREG is 1, and R1 takes -184.\n6. So the load's values cross five joins: FETCHED, IR, CONTROL, ADDR and MQ.",
  loadLead:
    'Press "Next edge" five times. At each edge, find which join, if any, carries the load\'s value.',
  failureExperiment:
    "Each part of this machine passes the tests it passed in its lesson. Those tests never covered a join. A join is tested only when the whole machine runs.\n\nThe figure runs the shop's program with one join held at a fixed value that you choose. Under the drawing, it compares the machine with the instruction-level model after every instruction and every trap, as every machine since Module 8 has been compared. It names the first place they disagree.\n\nThe three joins are: MQ, from the memory port to the datapath; NOHANDLER, from the datapath to the control unit, 1 when C4 is 0 or holds the PC; and CAUSE, from the control unit to the datapath.",
  faultsLead:
    'Choose a join, predict which instruction first goes wrong, then press "Run to the end".',
  faultMq:
    "With MQ held at 0, every load reads 0. After `R1 <= word[sensorA]` at `008`, R1 is 0 on the machine and -184 by the model. The run still stops: the gap is 0, so the display shows 0 and CLASH stays off. Nothing halts. Only the comparison shows the fault.",
  faultNoHandler:
    "With NOHANDLER held at 1, the trap logic sees no handler. At `call system`, at `03C`, the machine halts with cause `41`. The model does not. C4 holds `044`, set by the program's second line, but the control unit never learns it: the join between the datapath and the control unit carries the wrong bit.",
  faultCause:
    "With CAUSE held at `00`, the trap still happens, but the datapath receives the wrong cause. C3 takes `00`. C2 takes `03C`, not `040`. The selector that picks the return point reads the cause, and only cause `41` makes it pick the next instruction. So `resume` goes back to `call system`, which traps again, over and over. The figure cuts the run off after 300 edges. The comparison names C2 first.",
  explanation:
    "The whole machine is its parts and the joins between them. One block drives each join, and another block reads it.\n\nThe control unit decides what each edge does. It decodes the instruction in the IR, steps the controller through its states, and sends every control signal on the control bus. The datapath holds the registers, the PC, the IR and the control registers, and does the arithmetic. The memory port holds the ROM, the RAM and the devices, behind one address.\n\nTogether, the control unit and the datapath work out and run each instruction. That part of the machine is the **CPU**, the central processing unit. The memory port, and everything behind it, sits outside the CPU.\n\nA trap is the whole machine at work. The control unit sees the cause and sends TRAP. At the same edge, the datapath's control registers and its PC take their words, and the controller goes to FETCH.\n\nThe faults showed that a join can break the machine while every part still passes its own tests.",
  generalisation:
    "Every machine is built this way: parts, each tested alone, then joined. A part's tests cannot test its joins.\n\nThe joins are tested by running whole programs. After every instruction, the machine is compared with the instruction-level model, which works out in numbers what each instruction should do, with no gates. The course has done this for every machine since Module 8.\n\nThe comparison names the first instruction that disagrees. That is where to start looking: at the joins and the parts that instruction uses.\n\nThe CPU and the memory are separate blocks joined by a few buses: an address out, a word out, a word back. The same split holds in machines far larger than this one.",
  answersLead: "Read the drawing and the timing diagram, then run the tests.",
  c1Task:
    "1. Open the question's figure, or the failure experiment's, at its top level. For each of four buses, choose the block that drives it: the block the bus leaves from on its right side.\n   - HB, the word a store writes;\n   - WAITING, the events that wait for an interrupt;\n   - STATUS, C0's two bits;\n   - CAUSEM, the memory step's cause.\n2. Use the investigation's timing diagram. Count edges from the reset, and find two edges:\n   - the edge at which the IR takes `resume`'s word, `81000000`;\n   - the edge at which the PC takes the return point, `040`.\n3. There are 6 tests, one for each answer.",
  c1Hints: [
    "The idea: a bus is driven by the block whose right side it leaves. That block's outputs are on its right side. A bus enters the other blocks on their left side.",
    "A common mistake: choosing the block a bus enters. A bus enters the block that reads it, not the one that drives it.",
    "A smaller example: IR leaves the datapath on its right side and enters the control unit on its left. So the datapath drives IR.",
    "Part of the answer: HB and STATUS leave the same block. `resume` takes three edges, FETCH, READ and WRITE. The IR takes its word at the first of them.",
    "The whole answer: HB is driven by the datapath. WAITING is driven by the memory port. STATUS is driven by the datapath. CAUSEM is driven by the memory port. The IR takes `resume`'s word at edge 63, and the PC takes `040` at edge 65.",
  ],
  reflection:
    "You have seen the whole machine as its parts and their joins. You have also seen an instruction's words cross those joins, edge by edge.\n\nEach figure so far showed one view at a time: a drawing, a timing diagram or a table.\n\nThe next lesson asks a question. Can you watch one line of the shop's program at every level at once, from the line to the gates, edge by edge?",
  modelVsReality:
    "A real CPU has the same blocks, but it runs several instructions at once. While one instruction is at its MEMORY edge, the next is at its ALU edge, and the one after is being fetched.\n\nThis machine runs one instruction at a time. So every edge belongs to one instruction.\n\nNothing of the overlapping is taught here. It is named so you know where this machine stops being like a real one.",
} as const;
