// Copyright © 2026 Christopher Snow

// The words of the lesson whole-machine.
//
// Drafted by the course's prose process from briefs of checked facts
// (docs/notes/module-13-machine/briefs, briefs 1A to 1C), checked against the simulator, and
// placed here by the lesson's structure. Edit a fact here only after checking it; the lesson's
// facts test holds the numbers.

export const PROSE = {
  loadAfter:
    "1. Edge 8, FETCH: FETCHING is 1. ADDR carries the PC, `008`. FETCHED brings `380017D8`, and the IR takes it. This edge crosses the joins ADDR and FETCHED.\n2. Edge 9, READ: HA and HB take the registers the instruction names. The control unit has decoded the IR's word as a load (kind 3), so the controller goes on to ALU. This edge crosses the join IR.\n3. Edge 10, ALU: the ALU adds 0 and the constant, `7D8`. HR takes `7D8`. IR and CONTROL cross here: the control unit decodes the IR's word and sends the ALU's job, add, on CONTROL.\n4. Edge 11, MEMORY: ADDR carries HR, `7D8`, room A's sensor. MQ brings -184 back. MLOAD and HOLDM are 1, and HM takes -184. This edge crosses the joins ADDR and MQ.\n5. Edge 12, WRITE: WREG is 1, and R1 takes -184 inside the datapath. No join is crossed at this edge.\n6. So the load's value crosses five joins: FETCHED, IR, CONTROL, ADDR and MQ.",
  question:
    "Module 12 ended on a question: \"Every part was built, but in separate lessons, on separate drawings. Can you follow one of the shop's programs through the handler and down to the gates of the one machine that runs it?\"\n\nModule 0 asked the same from the top. The machine was a box that ran lines of a program. Its second lesson followed one line down to one wire, on a path chosen for you.\n\nThis module answers the question with the machine whose every part you have now built. This lesson asks which parts make the whole machine, and where they meet.\n\nThe figure below is the final machine, running the shop's program. That program is Module 0's first program for the shop, written again for this machine.",
  makersLead:
    "Open each of the three blocks in turn by pressing it. The table under the drawing names each part at the level on show and the module that built it.",
  makersAfter:
    "The top level has three blocks. The control unit (`control`) was built in Module 9 and grown in Modules 10 and 12. The datapath (`datapath`) was built in Module 8 and grown in Modules 9, 10 and 12. The memory port (`port`) was built in Module 9 and grown in Module 12.\n\nInside the datapath: the register file (Module 6), the ALU (Module 7), the PC (Module 8), the IR (Module 9) and the control registers (Module 12).\n\nInside the control unit: the decoder (Module 9, grown in Module 10), the controller (Module 9, grown in Module 12) and the trap logic (Module 12).\n\nInside the memory port: the memory (Module 6, grown in Modules 8, 9 and 12).",
  motivation:
    "The course's final machine is Module 12's machine of several edges, with its trap hardware. It also has the two instructions you added in your own copy: the call through a register, from Module 9, and set if, from Module 10.\n\nThe final machine needs two changes for those instructions. The decoder that Module 10's capstone built knows both new kinds, kind 9 and kind A. The datapath also has a fifth source for the word register Y takes, after HR, HM, PC + 4 and CWORD: MET as a word, 0 or 1, chosen by SET.\n\nThe machine is built from the course's own versions of the parts you designed, often wider. Its register file has sixteen registers of 64 bits, where Module 6's had four words of 4 bits. It does not run your own earlier answers: each lesson keeps its own work.\n\nA bus or a wire between two blocks, where one block's output becomes another's input, is called a **join**.\n\nThe three blocks pass values to each other across joins. The control unit sends CONTROL to the datapath and the memory port. CONTROL is the control bus: every control signal bundled into one bus. The datapath sends the instruction in the IR to the control unit, which decodes it. The memory port sends FETCHED, the word at the address ADDR names, to the datapath. At a FETCH edge ADDR carries the PC, and the IR takes FETCHED.\n\nA wire's name is written on the right side of the block that drives it, where its outputs are, and on the left side of each block it enters. Two kinds of exception apply. HB, the word a store writes, enters the memory port under another name, D. CLK, RST, DOOR, WARM, SENSORA and SENSORB are the machine's own inputs, and no block drives them. Only CLK and RST are drawn at the machine's left side. DOOR, WARM, SENSORA and SENSORB come in just left of the memory port, the block that reads them.\n\nAn instruction's words cross these joins edge by edge. The rest of this lesson follows them.",
  prediction:
    'The figure is paused after 47 edges. The next edge is the WRITE edge of `call R6, R15`, at `02C`, the call through a register, kind 9.\n\nThe shop\'s program, with its addresses, is folded inside this figure, between its controls and its drawing. Its line `R6 <= show` gives R6 the address of the line `show:`.\n\nNo value shows until you commit. Choose an answer and press "Check my prediction".',
  p1Question: "What does the PC hold after the next edge?",
  p1Explain:
    "The PC takes `034`, the address of `show:`. A call through a register takes R6 plus the constant, 0. R6 holds 52, which is `034`.\n\nAt the same edge R15 takes `030`, the PC plus 4: the line after the call, `stop`, where `goto R15` returns.\n\n`02C` is the call itself, and `000` is where the run began.",
  investigation:
    "The figure is a timing diagram of the shop's program. Each edge keeps its number from the reset. The figure runs from edge 57 to edge 64, which covers the system call, the handler's store, and the start of `resume`.\n\nIts lanes are signals that cross joins: FETCHED from the memory port to the datapath; IR from the datapath to the control unit; TRAP on the control bus to the datapath; CAUSE from the control unit to the datapath; ADDR from the datapath to the memory port. Lanes also show S, the controller's state, and the PC.\n\nThe cursor moves half an edge at a time: the clock's rise and its fall.",
  timelineLead: "Move the cursor edge by edge and find where each value crosses a join.",
  timelineAfter:
    "1. Edge 57 is the FETCH edge of `call system`, at `03C`. ADDR carries the PC, `03C`. FETCHED brings back `80000000`, and the IR takes it at edge 57.\n2. Before edge 58 the control unit has decoded the IR: TRAP is 1 and CAUSE is `41`. At edge 58, the READ edge, the PC takes `044`, the handler's address, C3 takes `41` and C2 takes `040`.\n3. Edges 59 to 62 run the handler's store, `word[display] <= R2`. At its MEMORY edge, edge 62, ADDR carries `7C0`, the display's address.\n4. At every FETCH edge ADDR carries the PC; at the other edges it carries HR, the ALU's held result.\n5. Edges 63 and 64 are `resume`'s FETCH and READ edges.",
  construction:
    "Follow one load, `R1 <= word[sensorA]` at `008`, edges 8 to 12. The figure is paused after edge 7. Find the route one question at a time.\n\n1. At edge 8, FETCH: which join brings the load's instruction word to the datapath, and which carries the address that word is read from?\n2. At edge 9, READ: which join tells the control unit what kind of instruction this is?\n3. At edge 10, ALU: open the datapath. Which join carries the ALU's job from the control unit?\n4. At edge 11, MEMORY: which join carries the address out, and which brings the reading back?\n5. At edge 12, WRITE: does the value cross a join at this edge?",
  loadLead:
    'Press "Next edge" five times. At each edge, find the join that carries the load\'s value, if any. The drawing marks the wires each edge uses.',
  failureExperiment:
    "Each part's design was tested in its own lesson. This machine runs the course's own versions of those parts, often wider. The faults below show that a join can break a machine whose parts each work.\n\nThe figure runs the shop's program with one join held at a fixed value you choose.\n\nUnder the drawing, the figure compares the machine with the instruction-level model, which works out in numbers what each instruction should do, with no gates. The comparison is made after every instruction and every trap. It names the first place where the machine and the model disagree. Every machine since Module 8 has been compared with it.\n\nThe three joins: MQ, from the memory port to the datapath; NOHANDLER, from the datapath to the control unit, 1 when C4 is 0 or holds the PC; and CAUSE, from the control unit to the datapath.\n\nEach fault's own paragraph shows under the drawing once its run has reached the end.",
  faultsLead:
    'Choose a join, predict which instruction first goes wrong, then press "Run to the end".',
  faultMq:
    "With MQ held at 0, every load reads 0. After `R1 <= word[sensorA]` at `008`, R1 is 0 on the machine and -184 by the model. The run still stops: the gap is 0, so the display shows 0 and CLASH stays off. Nothing halts. Only the comparison shows the fault.",
  faultNoHandler:
    "With NOHANDLER held at 1, the trap logic sees no handler. At `call system`, at `03C`, the machine halts with cause `41`. The model does not. C4 holds `044`, set by the program's second line, but the control unit never learns it: the join between the datapath and the control unit carries the wrong bit.",
  faultCause:
    "With CAUSE held at `00`, the trap still happens, but the datapath receives the wrong cause. C3 takes `00`. C2 takes `03C`, not `040`. The selector that picks the return point reads the cause, and only cause `41` makes it pick the next instruction. So `resume` goes back to `call system`, which traps again, over and over. The figure cuts the run off after 300 edges. The comparison names C2 first.",
  explanation:
    "The whole machine is its parts and the joins between them. One block drives each join, and another block reads it.\n\nThe control unit decides what each edge does. It decodes the instruction in the IR, steps the controller through its states, and sends every control signal on the control bus. The datapath holds the registers, the PC, the IR and the control registers, and does the arithmetic. The memory port holds the ROM, the RAM and the devices, each at its own range of addresses in one map.\n\nTogether, the control unit and the datapath work out and run each instruction. That part of the machine is the **CPU**, the central processing unit. The memory port, and everything behind it, sits outside the CPU.\n\nA trap is the whole machine at work. The control unit sees the cause and sends TRAP. At the edge that traps, the datapath's control registers and its PC take their words, and the controller goes to FETCH.",
  generalisation:
    "A join is tested only by running whole programs, compared with the model after every instruction. The comparison names the first instruction that disagrees: start looking at the joins and the parts that instruction uses.\n\nThe CPU and the memory are separate blocks joined by buses. Here there are eight: CONTROL, ADDR and HB go out to the memory port; FETCHED, MQ, CAUSEF, CAUSEM and WAITING come back. Machines far larger keep the same split.",
  answersLead: "Use the drawing for the four buses and work the two edges out, then run the tests.",
  c1Task:
    "1. Open the drawing's datapath or control unit. Find each bus by what it carries, and choose the part inside that block at its end, as the question names:\n   - the word a load brings back: which part inside the datapath takes it?\n   - the address the memory reads: which part inside the datapath drives it?\n   - the events that wait for an interrupt: which part inside the control unit reads them?\n   - C0's two bits: which part inside the datapath drives them?\n2. No figure runs this program. Work the edges out from the controller's states.\n\n   ```\n   000  R1 <= handler\n   004  C4 <= R1\n   008  R2 <= word[sensorB]\n   00C  call system\n   010  stop\n   014  handler: resume\n   ```\n\n   Count edges from the reset, edge 1 first. Find the edge at which the IR takes `resume`'s word, and the edge at which the PC takes the return point, `010`.\n3. There are 6 tests, one for each answer.",
  c1Hints: [
    "The idea: open the block the bus enters or leaves. A bus enters a part on its left and leaves a part on its right, inside a block as at the top. Find a bus by what it carries, as Modules 9 and 12 named it.",
    "A common mistake: choosing the part a bus's value comes from before it reaches the bus, such as the PC for ADDR, which reaches ADDR only through a selector.",
    "A smaller example, no part of the task: IR leaves the datapath from the part `ir`, on its right.",
    "Part of the answer: each kind passes through its own states. A constant job takes FETCH, READ, ALU and WRITE. Writing a control register, `C4 <= R1`, takes FETCH, READ and WRITE. A load takes FETCH, READ, ALU, MEMORY and WRITE. `call system` takes FETCH and READ, and traps at its READ edge. `resume` takes FETCH, READ and WRITE.",
    "The whole answer: `heldM` takes MQ; `pickAddr` drives ADDR; `trapLogic` reads WAITING; `cregs` drives STATUS; the IR takes `resume`'s word at edge 15, and the PC takes `010` at edge 17.",
  ],
  reflection:
    "You have seen the whole machine as its parts and their joins. A load's and a system call's words cross the joins edge by edge.\n\nCan you watch one line of the shop's program at every level at once, from the line to the gates, edge by edge?",
  modelVsReality:
    "A real CPU has the same blocks, but it runs several instructions at once. While one instruction is at its MEMORY edge, the next is at its ALU edge, the one after at READ, and the one after that being fetched.\n\nThis machine runs one instruction at a time. So every edge belongs to one instruction.\n\nNothing of the overlapping is taught here. It is named so you know where this machine stops being like a real one.",
} as const;
